Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-04, with the labels that each got.

#201 Some Repaired LV changes and makes a Repaired New Varadero variant
  code/__DEFINES/__game.dm
  code/modules/cm_marines/equipment/maps.dm
  map_config/maps.txt
  maps/map_files/LV624_Fixed/LV624_repaired.dmm
  maps/map_files/New_Varadero_Fixed/New_Varadero_Repaired.dmm
  maps/new_varadero_repaired.json
Labels: Mapping

#191 Upp sentry + sentry respirte by amory
  code/datums/ammo/bullet/special_ammo.dm
  code/modules/defenses/defenses.dm
  code/modules/defenses/handheld.dm
  code/modules/defenses/sentry.dm
  code/modules/projectiles/magazines/sentries.dm
  icons/obj/items/weapons/guns/ammo_by_faction/upp.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/structures/machinery/defenses/sentry.dmi
  maps/map_files/chapaev/chapaev.dmm
Labels: needs tested, Sprites, Mapping

#211 adds arnolds machete to loadout
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/client/preferences_gear.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/mob/humans/onmob/suit_slot.dmi
Labels: Sprites

#207 updated secure door icon palette
  icons/obj/structures/doors/securedoor.dmi
Labels: Sprites

#217 Tactical reload on the move
  code/modules/projectiles/gun_helpers.dm
Labels: Balance

#218 Fixes horizontal access denied sprite
  icons/obj/structures/doors/securedoor.dmi
Labels: Sprites

#224 machetes now have belt slot sprites
  icons/mob/humans/onmob/belt.dmi
Labels: Sprites

#196 M44 sprite and sound changes
  code/modules/projectiles/guns/revolvers.dm
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
Labels: Sprites

#232 Slightly reduces crusher spawn sound falloff
  code/modules/mob/living/carbon/xenomorph/castes/Crusher.dm
Labels: Quality of Life

#220 Empty Rifles in the Gun Racks
  code/game/objects/structures/gun_rack.dm
  code/modules/projectiles/guns/rifles.dm
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: Mapping

#229 Adds a new shipmap, the USS Heyst
  code/game/area/golden_arrow.dm
  code/global.dm
  map_config/shipmaps.txt
  maps/heyst.json
  maps/map_files/heyst/heyst.dmm
  maps/map_files/heyst/sprinkles/.gitkeep
Labels: Mapping

#227 adds silenced smartgun for gms to spawn
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/smartgun.dm
  icons/obj/items/weapons/guns/attachments/barrel.dmi
Labels: Sprites

#241 Conestogafication of the Golden Arrow
  code/global.dm
  map_config/shipmaps.txt
  maps/golden_arrow_classic.json
  maps/heyst.json
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/golden_arrow_classic/golden_arrow_classic.dmm
  maps/map_files/golden_arrow_classic/sprinkles/.gitkeep
  maps/map_files/heyst/heyst.dmm
Labels: do not merge, Mapping

#230 515 (the reckoning)
  .github/alternate_byond_versions.txt
  .github/workflows/ci_suite.yml
  .tgs.yml
  code/__DEFINES/__spacemandmm.dm
  code/__DEFINES/_macros.dm
  code/__HELPERS/nameof.dm
  code/_byond_version_compat.dm
  code/_experiments.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/mc/globals.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/ticker.dm
  code/datums/datum.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/devices/personal_data_transmitter.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/structures/pipes/pipes.dm
  code/game/world.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/client/client_procs.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/specialist/launcher/launcher.dm
  code/modules/reagents/chemistry_machinery/reagent_grinder.dm
  config/example/config.txt
  dependencies.sh
  tools/build/build.js
  tools/build/lib/byond.js
  tools/ci/download_od.sh
  tools/ci/run_od.sh
  tools/ci/setup_od.sh
Labels: UI, Github

#243 updates tgui list input
  code/modules/tgui/tgui_input_list.dm
  tgui/packages/tgui/interfaces/ListInputModal.tsx
Labels: UI

#244 emote and talking length
  code/global.dm
Labels: Quality of Life

#242 Some Golden Arrow changes
  code/datums/medal_awards.dm
  code/datums/paygrades/paygrade.dm
  code/game/machinery/ARES/ARES_procs.dm
  code/game/machinery/doors/brig_system.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping
