Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-10, with the labels that each got.

#493 Brings back PltCo medal awarding
  code/datums/medal_awards.dm
  code/datums/paygrades/paygrade.dm
Labels: Quality of Life

#479 Walkman Lore Edit
  code/game/objects/items/devices/walkman.dm
Labels: Feature, Quality of Life

#494 Allows Mk1 & NSG mag boxes to be carried on back (again?)
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
Labels: Quality of Life

#488 Green Balaclava fix
  icons/mob/humans/onmob/mask.dmi
Labels: fix, Sprites

#485 American Spirit
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/helmet.dm
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/obj/items/cigarettes.dmi
Labels: Sprites, Missing Changelog

#320 Kills weather site overlays
  code/datums/weather/weather_event.dm
  code/datums/weather/weather_events/big_red.dm
  code/datums/weather/weather_events/faction_clash.dm
  code/datums/weather/weather_events/lv624.dm
  code/datums/weather/weather_events/new_varadero.dm
  code/datums/weather/weather_events/sorokyne.dm
  code/modules/mob/living/living_defense.dm
Labels: Missing Changelog

#486 better floors
  icons/turf/almayer.dmi
  icons/turf/floors/floors.dmi
Labels: Sprites, Missing Changelog

#490 Replaces giant spider spirtes
  icons/mob/animal.dmi
Labels: Sprites

#484 EMERGENCY Gin bottle replacer
  icons/obj/items/drinks.dmi
Labels: Sprites, Missing Changelog

#489 Cultists can't see in the dark
  code/modules/gear_presets/other.dm
Labels: Missing Changelog

#505 Lets try this again: Makes cassette pouches hold slightly more tapes
  code/game/objects/items/storage/pouch.dm
Labels: Quality of Life, Balance

#502 O1 and O2 use pins instead of bars
  code/modules/clothing/under/rank_pins.dm
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/ties.dmi
Labels: Sprites, Missing Changelog

#499 Fix for "Kills weather site overlays"
  code/modules/mob/living/living_defense.dm
Labels: Missing Changelog

#498 No time-based ranks
  code/modules/gear_presets/upp.dm
  code/modules/gear_presets/uscm.dm
Labels: Removal

#511 Fire Support Menu GAU and Laser fixes
  code/modules/cm_marines/dropship_ammo.dm
Labels: fix

#513 10x28mm Ammo Box Addition
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Feature, Mapping

#501 US Armed Forces update 2; the search for more military-prop variety
  code/__DEFINES/job.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/paygrade_defs/marines.dm
  code/__DEFINES/paygrade_defs/navy.dm
  code/__DEFINES/radio.dm
  code/controllers/subsystem/communications.dm
  code/datums/paygrades/factions/uscm/marine.dm
  code/datums/paygrades/factions/uscm/navy.dm
  code/datums/skills/army.dm
  code/datums/skills/usasf.dm
  code/game/jobs/job/special/army.dm
  code/game/jobs/job/special/usasf.dm
  code/game/machinery/telecomms/presets.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/rank_pins.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/synths.dm
  code/modules/gear_presets/usa.dm
  code/modules/gear_presets/usasf.dm
  code/modules/mob/living/say.dm
  code/modules/projectiles/guns/rifles.dm
  colonialmarines.dme
  icons/mob/humans/onmob/eyes.dmi
  icons/mob/humans/onmob/suit_0.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/glasses.dmi
  icons/obj/items/clothing/suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/radio.dmi
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: needs tested, UI, Feature, Sprites, Grammar and Formatting

#519 Gives the new shades a mask-slot sprite
  icons/mob/humans/onmob/mask.dmi
Labels: Sprites

#514 Makes Dogtags removable on death immediately
  code/modules/mob/living/carbon/human/human_stripping.dm
Labels: Quality of Life

#510 [TM Ready] Chemical Weapons (CN20) in the FS Menu
  code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
  code/modules/cm_marines/dropship_ammo.dm
  code/modules/cm_marines/equipment/mortar/mortar_shells.dm
  code/modules/cm_marines/orbital_cannon.dm
  tgui/packages/tgui/interfaces/GameMasterFireSupportMenu.jsx
Labels: UI, Feature, Quality of Life

#526 Light CN20 Adjustment, axes leftover FS issues
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
  code/modules/cm_marines/equipment/mortar/mortar_shells.dm
Labels: Feature, Removal, Balance

#525 US Armed Forces update 3
  code/__DEFINES/skills.dm
  code/datums/skills/army.dm
  code/datums/skills/usasf.dm
  code/game/jobs/job/special/army.dm
  code/modules/gear_presets/synths.dm
Labels: fix, Feature, Quality of Life

#521 Minor ADS-C tweaks
  code/modules/vehicles/hardpoints/primary/aa_cannon.dm
Labels: Quality of Life

#508 [TM] Tougher Airlocks + Airlock Assemblies on Destruction
  code/__DEFINES/conflict.dm
  code/__DEFINES/xeno.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/objects/structures/airlock_assembly.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
Labels: Feature, Balance

#516 Sections From The Tech Man Are Now Properly Referenced
  code/__DEFINES/job.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/tl.dm
  code/game/jobs/job/marine/squad_info.dm
  code/game/jobs/job/marine/squads.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/gear_presets/uscm.dm
Labels: Quality of Life, Grammar and Formatting

#469 Xeno blood doesn't track
  code/game/blood.dm
  code/game/objects/effects/decals/cleanable/blood/blood.dm
Labels: Missing Changelog
