Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-08, with the labels that each got.

#311 CMB/MP gear loadout edits, Mod 88 edits, CMB/MP resprites
  code/datums/factions/clf.dm
  code/datums/factions/pmc.dm
  code/datums/factions/royalmarinescommando.dm
  code/game/machinery/vending/vending_types.dm
  code/game/machinery/vending/vendor_types/crew/pilot_officer.dm
  code/game/machinery/vending/vendor_types/crew/vehicle_crew.dm
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/machinery/vending/vendor_types/wo_vendors.dm
  code/game/objects/effects/spawners/faction_spawners.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/gear_presets/cmb.dm
  code/modules/gear_presets/uscm_police.dm
  code/modules/gear_presets/uscm_ship.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/vehicles/interior/interactable/vendors.dm
  icons/mob/humans/onmob/hands.dmi
  icons/mob/humans/onmob/head_0.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_0.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/weapons/guns/guns_by_faction/colony.dmi
  maps/map_files/CORSAT/Corsat.dmm
  maps/map_files/New_Varadero/New_Varadero.dmm
  maps/map_files/New_Varadero_Fixed/New_Varadero_Repaired.dmm
  maps/shuttles/ert_shuttle_big.dmm
Labels: Sprites

#321 Fire Support Menu for GM's
  code/modules/admin/admin_verbs.dm
  code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
  colonialmarines.dme
  tgui/packages/tgui/interfaces/GameMasterFireSupportMenu.jsx
Labels: UI, Feature, Admin

#340 GM button: toggle AI xeno weeding
  code/_globalvars/misc.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/game_master/extra_buttons/toggle_ai_xeno_weeding.dm
  code/modules/mob/living/carbon/xenomorph/ai/movement/drone.dm
  colonialmarines.dme
Labels: Feature

#350 Adds Railgun and it's variants to the game (Admin only)
  code/datums/skills/uscm.dm
  code/modules/cm_tech/implements/railgun.dm
Labels: Feature, Balance

#354 Fixes xenos pathing to unreachable target
  code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
Labels: fix

#359 Misc Fixes
  code/__DEFINES/dcs/signals/atom/mob/signals_mind.dm
  code/__DEFINES/dcs/signals/atom/mob/signals_mob.dm
  code/__DEFINES/dcs/signals/signals_client.dm
  code/__DEFINES/dcs/signals/signals_global.dm
  code/__DEFINES/sounds.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/minimap.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/datums/action.dm
  code/datums/components/overlay_lighting.dm
  code/datums/mind.dm
  code/datums/soundOutput.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/sound.dm
  code/modules/client/client_procs.dm
  code/modules/defenses/sentry_computer.dm
  code/modules/escape_menu/escape_menu.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/vehicles/van/van.dm
  colonialmarines.dme
  strings/metatips.txt
Labels: fix, Feature, Quality of Life, Code Improvement, Refactor, Grammar and Formatting

#360 Buff m56d
  code/datums/ammo/bullet/special_ammo.dm
  code/modules/cm_marines/smartgun_mount.dm
Labels: Balance

#355 Adds quick "Command Announcement" button for Game Masters
  code/modules/admin/admin_verbs.dm
  code/modules/admin/game_master/extra_buttons/marine_announce.dm
  colonialmarines.dme
Labels: Feature

#361 Game no longer freezes when spawning stuff
  html/create_object.html
Labels: Admin

#363 Black harness & eyepiece update
  code/modules/clothing/suits/marine_armor.dm
  icons/mob/humans/onmob/eyes.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/obj/items/clothing/cm_suits.dmi
Labels: Sprites

#365 Mirror '"Start Round" can start delayed round'
  code/controllers/subsystem/ticker.dm
Labels: Admin

#367 Taking the belt to SGs
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
Labels: Feature

#381 AI door interactions fixed
  code/__DEFINES/xeno_ai.dm
  code/game/machinery/doors/shutters.dm
  code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
Labels: fix, Code Improvement

#387 Platoon Leadership Timelocks
  code/game/jobs/job/antag/xeno/queen.dm
  code/game/jobs/job/civilians/other/liaison.dm
  code/game/jobs/job/civilians/other/reporter.dm
  code/game/jobs/job/civilians/other/survivors.dm
  code/game/jobs/job/civilians/support/cmo.dm
  code/game/jobs/job/civilians/support/doctor.dm
  code/game/jobs/job/civilians/support/nurse.dm
  code/game/jobs/job/civilians/support/researcher.dm
  code/game/jobs/job/command/auxiliary/auxiliary_support_officer.dm
  code/game/jobs/job/command/auxiliary/crew_chief.dm
  code/game/jobs/job/command/auxiliary/intel.dm
  code/game/jobs/job/command/auxiliary/pilot.dm
  code/game/jobs/job/command/auxiliary/senior.dm
  code/game/jobs/job/command/cic/executive.dm
  code/game/jobs/job/command/cic/staffofficer.dm
  code/game/jobs/job/command/police/chief_police.dm
  code/game/jobs/job/command/police/police.dm
  code/game/jobs/job/command/police/warden.dm
  code/game/jobs/job/logistics/cargo/chief_req.dm
  code/game/jobs/job/logistics/engi/chief_engineer.dm
  code/game/jobs/job/logistics/engi/ordnance_tech.dm
  code/game/jobs/job/marine/squad/engineer.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/smartgunner.dm
  code/game/jobs/job/marine/squad/specialist.dm
  code/game/jobs/job/marine/squad/tl.dm
  code/game/world.dm
Labels: Feature

#384 New Loadout Items (And some Adjustments)
  code/game/objects/items/storage/misc.dm
  code/modules/client/preferences_gear.dm
Labels: Feature

#334 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/README.md
  code/modules/tgs/core/README.md
  code/modules/tgs/core/byond_world_export.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
Labels: Tools

#390 Fixes missing gamemode bitfields
  code/_globalvars/bitfields.dm
Labels: Admin

#393 Mirror "Suit storages qdel pockets on Destroy()"
  code/modules/clothing/suits/storage.dm
Labels: PR'd upstream

#339 Dropship roster expansion
  code/__DEFINES/camera.dm
  code/__DEFINES/shuttles.dm
  code/game/area/Sulaco.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/camera_console.dm
  code/game/machinery/computer/dropship_weapons.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/objects/items/misc.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/turfs/closed.dm
  code/game/turfs/transit.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/cm_phone/phone_base.dm
  code/modules/cm_tech/implements/railgun.dm
  code/modules/dropships/attach_points/templates.dm
  code/modules/shuttle/computers/dropship_computer.dm
  code/modules/shuttle/dropship.dm
  code/modules/shuttle/shuttles/dropship.dm
  code/modules/vehicles/interior/interactable/seats.dm
  icons/obj/objects.dmi
  icons/obj/structures/doors/dropship4_cargo.dmi
  icons/obj/structures/doors/dropship4_pilot.dmi
  icons/obj/structures/doors/dropship4_side.dmi
  icons/obj/structures/doors/dropship4_side2.dmi
  icons/obj/structures/machinery/computer.dmi
  icons/obj/structures/machinery/shuttle-parts.dmi
  icons/turf/dropship.dmi
  icons/turf/dropship2.dmi
  icons/turf/dropship3.dmi
  icons/turf/dropship4.dmi
  maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
  maps/shuttles/dropship_cherokee.dmm
  maps/shuttles/dropship_cyclone.dmm
  maps/shuttles/dropship_midway.dmm
  maps/shuttles/dropship_tornado.dmm
  maps/shuttles/dropship_tripoli.dmm
  maps/shuttles/dropship_typhoon.dmm
  maps/shuttles/shuttle_size.dmm
Labels: Sprites, Mapping

#398 Cherokee kill
  maps/shuttles/dropship_cherokee.dmm
Labels: Feature, Mapping

#400 Delete shuttle_size.dmm
  maps/shuttles/shuttle_size.dmm
Labels: Feature, Mapping

#401 fixes dropship icon states
  maps/shuttles/dropship_midway.dmm
Labels: Feature, Mapping

#388 Galley Gaming
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#395 Adds ERP
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/reagents/chemistry_reactions/food_drink.dm
  code/modules/reagents/chemistry_reagents/drink.dm
  code/modules/reagents/chemistry_reagents/food.dm
  icons/obj/items/food.dmi
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Feature, Quality of Life

#403 fixes to parachuting
  code/game/turfs/transit.dm
  code/modules/shuttle/shuttles/dropship.dm
Labels: Feature

#392 Ports TG stripping menu from upstream
  code/__DEFINES/strippable.dm
  code/_macros.dm
  code/_onclick/click_hold.dm
  code/_onclick/drag_drop.dm
  code/datums/elements/strippable.dm
  code/game/objects/items/misc.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_stripping.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun_attachables.dm
  colonialmarines.dme
  icons/ui_icons/inventory/back.png
  icons/ui_icons/inventory/belt.png
  icons/ui_icons/inventory/collar.png
  icons/ui_icons/inventory/ears.png
  icons/ui_icons/inventory/glasses.png
  icons/ui_icons/inventory/gloves.png
  icons/ui_icons/inventory/hand_l.png
  icons/ui_icons/inventory/hand_r.png
  icons/ui_icons/inventory/head.png
  icons/ui_icons/inventory/id.png
  icons/ui_icons/inventory/mask.png
  icons/ui_icons/inventory/neck.png
  icons/ui_icons/inventory/pocket.png
  icons/ui_icons/inventory/shoes.png
  icons/ui_icons/inventory/suit.png
  icons/ui_icons/inventory/suit_storage.png
  icons/ui_icons/inventory/uniform.png
  tgui/packages/tgui/interfaces/StripMenu.tsx
  tgui/packages/tgui/styles/interfaces/StripMenu.scss
  tgui/packages/tgui/styles/main.scss
Labels: UI, Feature

#409 Solar Devils Patch update
  code/modules/client/preferences_gear.dm
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
Labels: Sprites

#408 Limited Service/Out of Service Equipment Adjustments
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/effects/landmarks/item_pool.dm
  code/game/objects/items/props/helmetgarb.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/cm_marines/equipment/guncases.dm
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/mob/humans/onmob/mask.dmi
  icons/obj/items/clothing/masks.dmi
  icons/obj/items/helmet_garb.dmi
Labels: Feature, Sprites, Removal

#413 Helmet Camo Covers
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/items/props/helmetgarb.dm
  code/modules/clothing/head/helmet.dm
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/obj/items/helmet_garb.dmi
Labels: Feature, Sprites

#417 Helmet Cover Shading Hotfix
  icons/mob/humans/onmob/helmet_garb.dmi
Labels: Sprites

#397 staying hydrated helps you regen blood
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/chemistry_reagents/other.dm
Labels: Feature

#405 adds support for non-standard underwear
  code/modules/client/preferences.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/new_player/sprite_accessories/underwear.dm
  icons/mob/humans/undershirt.dmi
Labels: Feature, Sprites

#366 Weighted Slotting
  code/__DEFINES/stats.dm
  code/__HELPERS/_lists.dm
  code/game/jobs/role_authority.dm
  code/modules/client/preferences.dm
Labels: do not merge, needs tested, Code Improvement

#394 AI valid target cache
  code/controllers/subsystem/xeno_ai.dm
  code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
Labels: Code Improvement

#425 Ammo resupply for VP70 and M4A3
  code/datums/factions/clf.dm
  code/game/objects/items/storage/misc.dm
  code/modules/projectiles/guns/revolvers.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping
