Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-03, with the labels that each got.

#129 gun racks
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/game/objects/structures/gun_rack.dm
  code/modules/cm_marines/equipment/guncases.dm
  colonialmarines.dme
  icons/obj/items/storage.dmi
  icons/obj/structures/gun_racks.dmi
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Sprites

#130 adrenaline changes
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Design

#131 STARS
  code/game/objects/items/misc.dm
  code/modules/shuttle/shuttles/dropship.dm
  icons/mob/hud/actions.dmi
  icons/obj/items/clothing/belts.dmi
  icons/turf/dropship.dmi
  maps/shuttles/dropship_midway.dmm
Labels: needs tested, Sprites

#128 PVE TONK BUFFS
  code/datums/ammo/bullet/tank.dm
  code/datums/ammo/rocket.dm
  code/modules/vehicles/hardpoints/armor/armor.dm
  code/modules/vehicles/hardpoints/armor/snowplow.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/autocannon_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/gl_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/ltb_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/tow_ammo.dm
  code/modules/vehicles/hardpoints/holder/tank_turret.dm
  code/modules/vehicles/hardpoints/primary/autocannon.dm
  code/modules/vehicles/hardpoints/primary/flamer.dm
  code/modules/vehicles/hardpoints/primary/ltb.dm
  code/modules/vehicles/hardpoints/primary/minigun.dm
  code/modules/vehicles/hardpoints/secondary/cupola.dm
  code/modules/vehicles/hardpoints/secondary/flamer.dm
  code/modules/vehicles/hardpoints/secondary/grenade_launcher.dm
  code/modules/vehicles/hardpoints/secondary/secondary.dm
  code/modules/vehicles/hardpoints/secondary/tow.dm
  code/modules/vehicles/hardpoints/support/artillery.dm
  code/modules/vehicles/hardpoints/support/iwsa.dm
  code/modules/vehicles/hardpoints/support/overdrive.dm
  code/modules/vehicles/hardpoints/wheels/treads.dm
  code/modules/vehicles/tank/tank.dm
Labels: Design

#138 FORECON-LRRP low pop platoon
  code/__DEFINES/job.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/shuttles.dm
  code/datums/factions/uscm.dm
  code/game/area/Sulaco.dm
  code/game/gamemodes/colonialmarines/ai/colonialmarines_ai.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/smartgunner.dm
  code/game/jobs/job/marine/squad/standard.dm
  code/game/jobs/job/marine/squad/tl.dm
  code/game/jobs/job/marine/squad_info.dm
  code/game/jobs/job/marine/squads.dm
  code/game/jobs/role_authority.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/turfs/closed.dm
  code/global.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/uscm.dm
  code/modules/shuttle/shuttles/dropship.dm
  icons/mob/hud/marine_hud.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/obj/items/clothing/cm_suits.dmi
  map_config/shipmaps.txt
  maps/map_files/rover/rover.dmm
  maps/map_files/rover/sprinkles/.gitkeep
  maps/rover.json
  maps/shuttles/dropship_cyclone.dmm
  maps/shuttles/dropship_upp.dmm
Labels: Sprites, Mapping

#141 shower sounds
  code/game/objects/structures/watercloset.dm
  code/game/sound.dm
  sound/effects/gurgle1.ogg
  sound/effects/gurgle2.ogg
  sound/effects/gurgle3.ogg
  sound/effects/gurgle4.ogg
Labels: Sound

#144 Brings back the pyro extinguisher for flamer
  code/modules/cm_marines/equipment/guncases.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: fix, Mapping

#145 replaces uscm fax machine with upp fax machine on chapaev
  maps/map_files/chapaev/chapaev.dmm
Labels: Mapping

#149 forecon SG no longer has camouflaged stuff
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/suits/marine_armor.dm
  maps/map_files/rover/rover.dmm
Labels: Mapping

#150 Facehuggers AI fix
  code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
  code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
Labels: fix

#152 SG Balloon alerts
  code/modules/projectiles/guns/smartgun.dm
Labels: Quality of Life

#134 GM infesting subpanel
  code/modules/admin/game_master/game_master.dm
  code/modules/admin/game_master/game_master_submenu/infest.dm
  colonialmarines.dme
  tgui/packages/tgui/interfaces/GameMasterSubmenuInfest.js
Labels: needs tested, UI, Feature

#135 VP78 Semi-Buff
  code/datums/ammo/bullet/pistol.dm
  code/modules/projectiles/guns/pistols.dm
Labels: Feature

#170 Implements sprite changes on behalf of AmoryBlane
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/uniforms.dmi
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Sprites, Mapping

#166 Smartgunner Presets Hotfix
  code/modules/gear_presets/dust_raider.dm
  code/modules/gear_presets/pmc.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/wo.dm
Labels: Removal

#171 Revert "Implements sprite changes to armor"
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/uniforms.dmi
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Sprites, Mapping

#164 AI tweaks and fixes
  code/__DEFINES/xeno_ai.dm
  code/controllers/subsystem/pathfinding.dm
  code/game/machinery/doors/poddoor.dm
  code/modules/mob/living/carbon/xenomorph/ai/movement/base_define.dm
  code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
Labels: fix, Feature, Code Improvement, Refactor

#178 Movie APC Mk2
  code/datums/skills/uscm.dm
  code/game/objects/structures/gun_rack.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/almayer/machinery.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/shuttle/computers/dropship_computer.dm
  code/modules/vehicles/interior/interactable/seats.dm
  code/modules/vehicles/interior/interactable/vehicle_locker.dm
  code/modules/vehicles/interior/interior_landmarks.dm
  icons/obj/structures/gun_racks.dmi
  icons/obj/structures/machinery/computer.dmi
  icons/obj/structures/machinery/toc.dmi
  icons/obj/structures/tables.dmi
  icons/obj/vehicles/interiors/apc.dmi
  icons/obj/vehicles/interiors/movie.dmi
  maps/interiors/apc_movie.dmm
Labels: Sprites, Mapping

#185 Adds boiler suits to Platoon Commander lockers
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#175 Implements sprite changes made by AmoryBlaine
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/uniforms.dmi
Labels: Sprites

#154 Ports a few Dropship PRs
  code/__DEFINES/dropships.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/multi_tile.dm
  code/modules/shuttle/computers/escape_pod_computer.dm
  code/modules/shuttle/helpers.dm
  code/modules/shuttle/shuttles/dropship.dm
  icons/obj/structures/doors/dropship1_side2.dmi
  icons/obj/structures/doors/dropship2_side2.dmi
  maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
  maps/shuttles/dropship_alamo.dmm
  maps/shuttles/dropship_cyclone.dmm
  maps/shuttles/dropship_midway.dmm
  maps/shuttles/dropship_normandy.dmm
  tgui/packages/tgui/interfaces/DropshipFlightControl.tsx
Labels: UI, Feature, Sprites, Mapping

#195 PVE animation update.
  icons/mob/xenos/crusher.dmi
  icons/mob/xenos/drone.dmi
  icons/mob/xenos/lurker.dmi
  icons/mob/xenos/runner.dmi
  icons/mob/xenos/wounds.dmi
Labels: fix, Feature, Sprites

#199 Jungle Update fix
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/uniform_0.dmi
Labels: Sprites

#200 Removes crafty pvts, redundant health hud.
  code/datums/skills/uscm.dm
  code/modules/gear_presets/cmb.dm
  code/modules/gear_presets/dust_raider.dm
  code/modules/gear_presets/fun.dm
  code/modules/gear_presets/uscm.dm
Labels: Removal, Balance

#165 Build order rewamp
  code/__DEFINES/xeno_ai.dm
  code/datums/components/xeno/ai_behavior_overrides/build_override_behavior.dm
Labels: fix, Code Improvement
