Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-11, with the labels that each got.

#532 Locker Fixes
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: fix, Mapping, Grammar and Formatting

#389 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools

#534 Fixes the rest of the missed Section Sergeant related things
  code/game/jobs/job/marine/squads.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/gear_presets/uscm.dm
  tgui/packages/tgui/interfaces/OverwatchConsole.jsx
  tgui/packages/tgui/interfaces/SquadInfo.tsx
Labels: fix, UI

#533 m56d has proper IFF again
  code/datums/ammo/bullet/rifle.dm
  code/modules/cm_marines/smartgun_mount.dm
Labels: Missing Changelog

#541 Alternate fence buff approach
  code/game/objects/structures/fence.dm
Labels: Quality of Life

#537 Doors Updated
  code/game/machinery/doors/airlock_types.dm
  icons/obj/structures/doors/2x1personaldoor.dmi
  icons/obj/structures/doors/2x1personaldoor_glass.dmi
  icons/obj/structures/doors/medidoor_plain.dmi
  icons/obj/structures/doors/personaldoor.dmi
  icons/obj/structures/doors/personaldoor_glass.dmi
  icons/obj/structures/doors/securedoor_glass.dmi
Labels: Sprites, Missing Changelog

#540 Adjusts tools the surgical case can hold.
  code/game/objects/items/storage/firstaid.dm
Labels: Balance

#543 Makes weed not cost half your loadout points
  code/game/objects/items/tools/flame_tools.dm
  code/modules/client/preferences_gear.dm
Labels: Missing Changelog

#548 Custom Armor Hotfix
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
Labels: fix, Sprites

#547 Jungle USCM overhaul
  code/__DEFINES/equipment.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/structures/crates_lockers/closets/secure/marine_personal.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/clothing/suits/marine_armor/smartgunner.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/Donator_Items.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/uscm_police.dm
  code/modules/gear_presets/uscm_ship.dm
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/clothing/uniforms.dmi
  maps/map_files/USS_Almayer/USS_Almayer.dmm
  maps/map_files/derelict_almayer/derelict_almayer.dmm
Labels: Sprites, Mapping, Missing Changelog

#553 Fixes the missing Hummingbird pistols
  code/datums/supply_packs/black_market.dm
  code/game/objects/items/storage/misc.dm
  maps/map_files/LV624_Fixed/LV624_repaired.dmm
Labels: fix, Mapping

#563 De-USCMifies the berets
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/head.dm
Labels: Grammar and Formatting

#567 hula girl dancing
  code/game/objects/structures/props.dm
Labels: Feature

#549 Let Vehicle Hardpoints Sprite Click
  code/modules/vehicles/hardpoints/hardpoint.dm
Labels: fix

#562 Tactical Map Update Cooldown
  code/controllers/subsystem/minimap.dm
Labels: Balance

#564 Dropship Weapons Reflavor
  code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
  code/modules/cm_marines/dropship_ammo.dm
  code/modules/cm_marines/dropship_equipment.dm
Labels: UI, Feature, Quality of Life, Removal

#538 US Armed Forces update 5 (More Army stuff this time)
  code/__DEFINES/job.dm
  code/datums/paygrades/factions/uscm/army.dm
  code/datums/paygrades/factions/uscm/navy.dm
  code/datums/skills/army.dm
  code/datums/skills/usasf.dm
  code/game/jobs/job/special/army.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor/intel.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/usa.dm
  code/modules/gear_presets/usasf.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist/launcher/rocket_launcher.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
Labels: Feature, Sprites, Quality of Life, Balance

#542 spawn dead and burst humans in create humans
  code/modules/admin/topic/topic_events.dm
  html/create_humans.html
Labels: Feature

#560 M15 Pin pulling sfx
  code/game/objects/items/explosives/grenades/marines.dm
  sound/weapons/pinpull.ogg
Labels: Sound, Missing Changelog

#568 Ports Dying Light from PVP CM
  code/game/objects/effects/aliens.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/ammo_boxes/misc_boxes.dm
  code/modules/projectiles/guns/flare_gun.dm
Labels: Feature, Code Improvement, Balance

#565 White M10 in vendor removed
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
Labels: Missing Changelog

#572 Alternative nuclear deployment method
  code/game/machinery/nuclearbomb.dm
  icons/mob/humans/onmob/back.dmi
  icons/obj/items/marine-items.dmi
Labels: Feature, Sprites

#576 Dropship door fix
  code/game/machinery/doors/airlock_types.dm
Labels: fix

#578 UPP Heavy armour internal-storage fix
  code/modules/clothing/suits/marine_armor/ert.dm
Labels: fix
