Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-06, with the labels that each got.

#274 Colored Campfire Light
  code/game/objects/structures/props.dm
Labels: Feature

#269 Port vehicle PRs
  code/_onclick/adjacent.dm
  code/datums/ammo/misc.dm
  code/datums/ammo/rocket.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/apc/apc.dm
  code/modules/vehicles/hardpoints/hardpoint.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/gl_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/tow_ammo.dm
  code/modules/vehicles/hardpoints/holder/tank_turret.dm
  code/modules/vehicles/hardpoints/primary/autocannon.dm
  code/modules/vehicles/hardpoints/primary/dual_cannon.dm
  code/modules/vehicles/hardpoints/primary/flamer.dm
  code/modules/vehicles/hardpoints/primary/ltb.dm
  code/modules/vehicles/hardpoints/primary/minigun.dm
  code/modules/vehicles/hardpoints/secondary/cupola.dm
  code/modules/vehicles/hardpoints/secondary/flamer.dm
  code/modules/vehicles/hardpoints/secondary/frontal_cannon.dm
  code/modules/vehicles/hardpoints/secondary/grenade_launcher.dm
  code/modules/vehicles/hardpoints/secondary/tow.dm
  code/modules/vehicles/hardpoints/special/firing_port_weapon.dm
  code/modules/vehicles/hardpoints/support/flare.dm
Labels: Quality of Life

#225 Fixes three instances of a negative accuracy bonus
  code/datums/ammo/bullet/pistol.dm
Labels: Feature

#271 SDQL2 bugfixes & features
  .github/CODEOWNERS
  code/controllers/subsystem/statpanel.dm
  code/game/objects/effects/effect.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_parser.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
Labels: Github, Admin

#252 Replaces shipside chemical machines with a vendor
  code/game/machinery/vending/vendor_types/medical.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  icons/obj/items/chemistry.dmi
  icons/obj/structures/machinery/vending.dmi
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: Feature, Sprites, Mapping, Removal

#256 engineering vic
  code/datums/vehicles.dm
  code/modules/vehicles/tank/aev.dm
  colonialmarines.dme
  icons/obj/vehicles/interiors/tank.dmi
  icons/obj/vehicles/tank.dmi
  maps/interiors/aev.dmm
Labels: Sprites, Mapping

#262 forecon tweaks and fixes
  code/datums/skills/uscm.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/game/objects/structures/gun_rack.dm
  code/modules/gear_presets/uscm.dm
  code/modules/projectiles/ammo_boxes/ammo_boxes.dm
  code/modules/projectiles/ammo_boxes/box_structures.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/attachments/under.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/structures/gun_racks.dmi
  maps/map_files/rover/rover.dmm
  maps/shuttles/dropship_cyclone.dmm
Labels: Sprites, Mapping

#255 GM Sound Panel [WIP]
  code/__DEFINES/sounds.dm
  code/datums/soundOutput.dm
  code/game/sound.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/game_master/sound_panel.dm
  colonialmarines.dme
  tgui/packages/tgui/interfaces/SoundPanel.tsx
Labels: UI, Feature

#291 Vulture Touchups & Fixes
  code/game/objects/items/pamphlets.dm
  code/game/objects/structures/vulture_spotter.dm
  code/modules/projectiles/guns/boltaction.dm
Labels: fix, Balance

#209 Misc Marine Changes and Fixes
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/belts.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/clothing/uniforms.dmi
  icons/obj/items/storage.dmi
Labels: Sprites

#285 ports skin colors and body types and
  code/__HELPERS/icons.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/sanitize_values.dm
  code/_globalvars/global_lists.dm
  code/datums/datacore.dm
  code/defines/procs/records.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/gear_presets/fun.dm
  code/modules/gear_presets/yautja.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/species/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/synthetic.dm
  code/modules/mob/living/carbon/human/species/working_joe/_species.dm
  code/modules/mob/living/carbon/human/species/yautja/_species.dm
  code/modules/mob/new_player/body.dm
  code/modules/mob/new_player/body_type.dm
  code/modules/mob/new_player/ethnicity.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/skin_color.dm
  code/modules/mob/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/new_player/sprite_accessories/underwear.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/limbs.dm
  colonialmarines.dme
  icons/mob/humans/species/r_human.dmi
  icons/mob/humans/species/r_predator.dmi
  icons/mob/humans/undershirt.dmi
  icons/mob/humans/underwear.dmi
Labels: Sprites

#294 Lets marines bring cassette tapes from home.
  code/modules/client/preferences_gear.dm
Labels: Feature

#297 Coolifies the ARC
  code/modules/almayer/machinery.dm
  icons/obj/vehicles/interiors/arc.dmi
  maps/interiors/arc.dmm
Labels: Feature, Sprites, Mapping

#299 Updated Spearhead Sprites
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/obj/items/clothing/belts.dmi
  icons/obj/items/weapons/guns/guns_by_faction/colony.dmi
  icons/obj/items/weapons/guns/lineart.dmi
Labels: Sprites

#314 RMC Redesign
  code/modules/clothing/shoes/marine_shoes.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/feet.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/obj/items/clothing/belts.dmi
  icons/obj/items/clothing/cm_hats.dmi
Labels: Sprites
