Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-05, with the labels that each got.

#208 Marine Weapon Repalettes
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/binoculars.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/back.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_obj.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_righthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/suit_slot.dmi
Labels: Sprites

#253 smoll lifeboat
  code/__DEFINES/shuttles.dm
  code/modules/shuttle/shuttles/crashable/lifeboats.dm
  maps/shuttles/lifeboat-compact.dmm
Labels: Mapping

#258 Dropship port door dir correction
  maps/shuttles/dropship_alamo.dmm
  maps/shuttles/dropship_cyclone.dmm
  maps/shuttles/dropship_midway.dmm
  maps/shuttles/dropship_normandy.dmm
Labels: Mapping

#214 Adds the ARC to the epic APC roster
  code/datums/vehicles.dm
  code/modules/vehicles/apc/arc.dm
  code/modules/vehicles/apc/arc_weaponless.dm
  code/modules/vehicles/apc/interior.dm
  code/modules/vehicles/hardpoints/primary/arc_frontal.dm
  code/modules/vehicles/hardpoints/wheels/apc_wheels.dm
  code/modules/vehicles/interior/areas.dm
  colonialmarines.dme
  icons/obj/vehicles/arc.dmi
  icons/obj/vehicles/hardpoints/arc.dmi
  icons/obj/vehicles/interiors/arc.dmi
  icons/obj/vehicles/interiors/arc_chassis.dmi
  icons/turf/areas_interiors.dmi
  maps/interiors/arc.dmm
Labels: Sprites, Mapping

#257 Tank weapon IFF
  code/modules/vehicles/hardpoints/holder/tank_turret.dm
  code/modules/vehicles/hardpoints/primary/autocannon.dm
  code/modules/vehicles/hardpoints/primary/ltb.dm
  code/modules/vehicles/hardpoints/primary/minigun.dm
  code/modules/vehicles/hardpoints/secondary/tow.dm
Labels: Quality of Life

#263 Tank "passenger" capacity
  code/modules/vehicles/tank/tank.dm
Labels: Quality of Life

#265 M5 Gasmask now functions
  code/game/objects/items/props/helmetgarb.dm
Labels: Feature
