Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-12, with the labels that each got.

#583 Port: Fix Werror handling in build script
  tools/build/lib/byond.js
Labels: UI, Missing Changelog

#517 Grenades expansion & overhaul
  code/datums/ammo/shrapnel.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/projectiles/ammo_boxes/grenade_packets.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  icons/obj/items/storage/packets.dmi
  icons/obj/items/weapons/grenade.dmi
  sound/weapons/grenade.ogg
Labels: Feature, Sprites, Quality of Life, Sound

#557 non-military ammo nerf
  code/datums/ammo/bullet/pistol.dm
  code/datums/ammo/bullet/revolver.dm
  code/datums/ammo/bullet/rifle.dm
  code/datums/ammo/bullet/smg.dm
  code/datums/ammo/bullet/sniper.dm
  code/datums/ammo/bullet/special_ammo.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance

#607 Naval Infantry PltCo
  code/modules/clothing/suits/marine_coat.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/gear_presets/uscm_ship.dm
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/uniforms.dmi
  maps/map_files/chapaev/chapaev.dmm
Labels: Feature, Sprites, Mapping

#612 Fix linters port + bump python
  dependencies.sh
  tools/requirements.txt
Labels: Github, Missing Changelog

#620 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools, Missing Changelog

#622 UPP Helmet Fixes
  code/modules/clothing/head/helmet.dm
  icons/mob/humans/onmob/helmet_garb.dmi
Labels: Sprites

#621 Dropship Tornado has pieces from Dropship Typhoon, this PR makes it not have those
  maps/shuttles/dropship_tornado.dmm
Labels: Mapping

#590 Cowboys and Detectives
  code/modules/clothing/head/misc.dm
  icons/mob/humans/onmob/head_0.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/obj/items/clothing/cm_hats.dmi
Labels: Feature, Sprites, Removal

#584 CAS Equipment Tweaks
  code/modules/cm_marines/dropship_ammo.dm
Labels: Balance

#577 Lessens Corpsman-suffering for greenshifts
  code/__DEFINES/chemistry.dm
  code/modules/reagents/chemistry_properties/prop_neutral.dm
  code/modules/reagents/chemistry_reagents/alcohol.dm
Labels: Quality of Life

#515 Bayonets no longer mount on M41A, UGL no longer removable
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Missing Changelog

#589 makes CPR not give you bad advice
  code/game/objects/items/tools/experimental_tools.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Grammar and Formatting

#626 M41A & Binocular Palette Update
  code/game/objects/items/devices/binoculars.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/binoculars.dmi
  icons/obj/items/devices.dmi
  icons/obj/items/weapons/guns/attachments/barrel.dmi
  icons/obj/items/weapons/guns/attachments/under.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_righthand.dmi
Labels: Feature, Sprites, Removal

#559 USCM Aux Roles, Alt Camo Overhaul and Soul Enforcement
  code/datums/emergency_calls/cryo_marines.dm
  code/datums/emergency_calls/cryo_marines_heavy.dm
  code/datums/emergency_calls/cryo_spec.dm
  code/datums/emergency_calls/tank_crew.dm
  code/datums/skills/uscm.dm
  code/game/jobs/job/marine/squad/specialist.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/machinery/vending/vendor_types/wo_vendors.dm
  code/game/objects/items/props/helmetgarb.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/large_holster.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/clothing/suits/marine_coat.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/colonist.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/uscm_police.dm
  code/modules/gear_presets/uscm_ship.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/new_player/sprite_accessories/underwear.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/eyes.dmi
  icons/mob/humans/onmob/head_0.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/mob/humans/onmob/mask.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/mob/humans/onmob/uniform_1.dmi
  icons/mob/humans/undershirt.dmi
  icons/mob/humans/underwear.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/glasses.dmi
  icons/obj/items/clothing/hats.dmi
  icons/obj/items/clothing/pouches.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/clothing/uniforms.dmi
  icons/obj/items/helmet_garb.dmi
  maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
  maps/map_files/rover/rover.dmm
Labels: Feature, Sprites, Mapping, Removal

#582 wall leaning
  code/__DEFINES/dcs/signals/atom/mob/living/signals_human.dm
  code/__DEFINES/traits.dm
  code/_onclick/human.dm
  code/game/turfs/walls/walls.dm
  icons/effects/effects.dmi
Labels: Feature, Sprites

#596 Prime Roll, Tutorial, & Player Weight Change
  code/datums/entities/player.dm
  code/game/jobs/job/job.dm
  code/game/jobs/role_authority.dm
  code/modules/client/preferences.dm
  code/modules/mob/new_player/new_player.dm
Labels: Quality of Life, Balance

#627 Increasing Admin Sound upload limit
  code/modules/client/client_procs.dm
Labels: Missing Changelog
