Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-02, with the labels that each got.

#112 free gradient
  code/modules/character_traits/hair_dye.dm
Labels: Feature

#113 Adds the on-mob bomber jacket sprites
  icons/mob/humans/onmob/suit_1.dmi
Labels: Sprites

#118 Update ice_colony_v2.json
  code/__DEFINES/__game.dm
  code/modules/cm_marines/equipment/maps.dm
Labels: fix

#116 APC buffs
  code/datums/ammo/bullet/tank.dm
  code/modules/vehicles/apc/apc.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/cupola_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/dualcannon_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/flare_launcher_ammo.dm
  code/modules/vehicles/hardpoints/primary/dual_cannon.dm
  code/modules/vehicles/hardpoints/secondary/frontal_cannon.dm
  code/modules/vehicles/hardpoints/support/flare.dm
  code/modules/vehicles/hardpoints/wheels/apc_wheels.dm
  code/modules/vehicles/multitile/multitile.dm
Labels: Quality of Life, Balance

#119 New UPP/UA/Prison boiler fatigues
  code/game/objects/items/storage/backpack.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/feet.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/backpacks.dmi
  icons/obj/items/clothing/suits.dmi
  icons/obj/items/clothing/uniforms.dmi
Labels: Feature, Sprites

#126 Implements M1911 pistol into Loadout Options and changes its sprite.
  code/game/objects/items/storage/misc.dm
  code/modules/client/preferences_gear.dm
  icons/obj/items/clothing/belts.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
Labels: Sprites
