Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-09, with the labels that each got.

#378 Cryo loadout changes + locker stuff
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/uscm_ship.dm
  code/modules/mob/new_player/preferences_setup.dm
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#414 PvP Snow Uniform Port
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/uniforms.dmi
Labels: Sprites

#426 Flap Cap Fixes and Smartgun Rename
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/guns/smartgun.dm
  icons/mob/humans/onmob/head_1.dmi
  icons/obj/items/clothing/cm_hats.dmi
Labels: fix, Sprites

#404 md blips now show to people in 1 tile radius
  code/game/objects/items/devices/motion_detector.dm
Labels: Feature

#410 Sorokyne Strata Patch
  code/game/machinery/vending/vending_types.dm
  maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
Labels: fix, Feature, Mapping, Removal

#431 Equalizes toolbelts & tool pouches max_w_class
  code/game/objects/items/storage/belt.dm
Labels: Quality of Life

#439 SG Belt Fix
  code/game/objects/items/storage/belt.dm
Labels: fix

#407 King port, PVE edition
  code/__DEFINES/mobs.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/misc.dm
  code/datums/langchat/langchat.dm
  code/datums/xeno_shields/shield_types/king_shield.dm
  code/datums/xeno_shields/xeno_shield.dm
  code/game/jobs/role_authority.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/effects/temporary_visuals.dm
  code/modules/admin/game_master/game_master.dm
  code/modules/admin/player_panel/actions/transform.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/abilities/king/king_abilities.dm
  code/modules/mob/living/carbon/xenomorph/abilities/king/king_macros.dm
  code/modules/mob/living/carbon/xenomorph/abilities/king/king_powers.dm
  code/modules/mob/living/carbon/xenomorph/abilities/ravager/ravager_powers.dm
  code/modules/mob/living/carbon/xenomorph/abilities/xeno_action.dm
  code/modules/mob/living/carbon/xenomorph/castes/king.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  colonialmarines.dme
  icons/effects/96x96.dmi
  icons/effects/heavyimpact.dmi
  icons/mob/xenos/king.dmi
  icons/mob/xenos/overlay_effects64x64.dmi
  icons/mob/xenos/roguedamage.dmi
  icons/mob/xenos/rogueking.dmi
  icons/mob/xenos/structures64x64.dmi
  icons/obj/structures/alien/xenoKingHatchery.dmi
  sound/voice/deep_alien_screech.ogg
  sound/voice/deep_alien_screech2.ogg
  sound/voice/king_background.ogg
Labels: Feature, Sprites, Sound

#440 Remove King from GM panel
  code/modules/admin/game_master/game_master.dm
Labels: Admin

#441 Reintroduces galley changes
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: fix, Mapping

#427 TNR handheld
  code/game/objects/items/devices/flashlight.dm
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/obj/items/lighting.dmi
Labels: Sprites

#383 LT prefs menu
  code/__DEFINES/__game.dm
  code/_globalvars/global_lists.dm
  code/game/jobs/job/job.dm
  code/game/jobs/role_authority.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/admin/game_master/extra_buttons/rename_platoon.dm
  code/modules/admin/verbs/select_equipment.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/uscm_ship.dm
Labels: Feature

#436 Adds a 'slot nickname' field for easily ID'ing chara slots
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: UI, Quality of Life

#423 Muted Janitorial Carts and Cleaner bottles
  code/game/objects/items/reagent_containers/spray.dm
  code/game/objects/structures/janicart.dm
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/obj/items/spray.dmi
  icons/obj/janitor.dmi
Labels: Sprites

#449 Overhauls the synthetics vendors
  code/game/machinery/vending/vendor_types/crew/synthetic.dm
Labels: fix, Feature, Quality of Life, Removal, Balance

#448 add flamer fueltank pouches to the garrow
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
Labels: Mapping, Missing Changelog

#446 Hair Fix
  icons/mob/humans/human_hair.dmi
Labels: Sprites, Missing Changelog

#443 Return of the M37
  code/modules/cm_marines/equipment/guncases.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Feature, Mapping, Removal

#459 removes random table in briefing
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping, Missing Changelog

#467 Spearhead onmob icon fix
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
Labels: Sprites, Missing Changelog

#470 Uncoloured prefab window
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  icons/turf/walls/ice_colony/shiva_windows.dmi
Labels: Sprites, Missing Changelog

#478 Medical vendor Create&Destroy fix
  code/game/machinery/vending/vendor_types/medical.dm
Labels: Missing Changelog

#475 M41 Magazine Can Sprite Fix
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
Labels: Missing Changelog

#466 literally just empty gun racks
  code/game/objects/structures/gun_rack.dm
Labels: Missing Changelog

#465 Folders, Notepad and Book Icon Updates and new props
  code/game/objects/items/books/book.dm
  code/game/objects/items/books/manuals.dm
  code/game/objects/prop.dm
  code/modules/paperwork/folders.dm
  icons/obj/items/books.dmi
  icons/obj/items/notepads.dmi
  icons/obj/items/paper.dmi
Labels: Sprites, Missing Changelog

#444 sadar buffs
  code/datums/ammo/rocket.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist/launcher/rocket_launcher.dm
Labels: Balance

#460 Interim Removal Of CLF Special Gear
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/clf.dm
Labels: Missing Changelog

#429 Adds the M579 Aerial-Defence System Carrier (AKA, the AA-APC, or LAV-AD of the future)
  code/datums/ammo/bullet/special_ammo.dm
  code/datums/ammo/rocket.dm
  code/datums/vehicles.dm
  code/game/objects/structures/gun_rack.dm
  code/modules/vehicles/apc/apc_aa.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/cupola_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/tow_ammo.dm
  code/modules/vehicles/hardpoints/primary/aa_cannon.dm
  code/modules/vehicles/hardpoints/secondary/aa_launcher.dm
  code/modules/vehicles/interior/areas.dm
  code/modules/vehicles/interior/interactable/viewports.dm
  code/modules/vehicles/interior/interior_landmarks.dm
  colonialmarines.dme
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/vehicles/hardpoints/apc.dmi
  icons/obj/vehicles/hardpoints/tank.dmi
  icons/obj/vehicles/interiors/apc.dmi
  icons/obj/vehicles/interiors/general.dmi
  icons/obj/vehicles/movieapc.dmi
  icons/turf/areas_interiors.dmi
  maps/interiors/apc_aa.dmm
Labels: fix, Feature, Sprites, Mapping

#473 M5 standardized
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/machinery/vending/vendor_types/wo_vendors.dm
  code/game/objects/items/props/helmetgarb.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/mob/humans/onmob/mask.dmi
  icons/obj/items/clothing/masks.dmi
Labels: Sprites, Missing Changelog

#481 Updates synth's headset tracking options
  code/game/objects/items/devices/radio/headset.dm
Labels: Quality of Life

#463 Tacmap access for main platoon
  code/controllers/subsystem/minimap.dm
  code/modules/cm_marines/overwatch.dm
Labels: UI

#416 Russian Patois
  code/__DEFINES/language.dm
  code/modules/character_traits/languages.dm
  code/modules/mob/language/languages.dm
  code/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: UI, Missing Changelog

#464 railgun should probably be able to see flares
  code/modules/cm_tech/implements/railgun.dm
Labels: Missing Changelog

#468 US Armed Forces update framework
  code/__DEFINES/paygrade_defs/army.dm
  code/__DEFINES/paygrade_defs/navy.dm
  code/datums/paygrades/factions/uscm/army.dm
  code/datums/paygrades/factions/uscm/navy.dm
  code/datums/paygrades/paygrade.dm
  code/modules/clothing/under/rank_pins.dm
  colonialmarines.dme
Labels: Feature, Code Improvement

#471 Removes HEFA Knights Reference From Big Red
  maps/map_files/BigRed/BigRed.dmm
Labels: Mapping, Removal

#491 Fixes the Automag selection in the loadout
  code/modules/client/preferences_gear.dm
Labels: fix
