Repository cmss13-devs/cmss13-pve, pull requests merged in 2024-07, with the labels that each got.

#288 Vehicle crashing tweaks
  code/modules/vehicles/multitile/multitile_movement.dm
Labels: fix

#315 GM Resin Panel
  code/modules/admin/admin_verbs.dm
  code/modules/admin/game_master/resin_panel.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/mob/living/carbon/xenomorph/abilities/general_powers.dm
  colonialmarines.dme
  tgui/packages/tgui/interfaces/ResinPanel.tsx
Labels: UI, Feature

#324 Special Buck Icon
  code/datums/ammo/bullet/shotgun.dm
  code/modules/projectiles/magazines/shotguns.dm
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/handful.dmi
Labels: Feature, Sprites

#331 GM Radio Clarity example message
  code/modules/admin/game_master/game_master.dm
  tgui/packages/tgui/interfaces/GameMaster.js
Labels: UI, Admin

#332 ARC projectile origin adjustment
  code/modules/vehicles/hardpoints/primary/arc_frontal.dm
Labels: Quality of Life

#292 sg sprites + flak jacket accessory (redone)
  code/modules/client/preferences_gear.dm
  code/modules/clothing/under/ties.dm
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
Labels: Sprites

#337 Fix quadtree AABB issue
  code/datums/quadtree.dm
Labels: fix

#341 Remove automatic end of round vote and reboot
  code/controllers/subsystem/ticker.dm
Labels: Removal

#345 Adds freed mob jobban
  code/modules/admin/banjob.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Admin

#343 Port "SStechtree startup optimisation"
  code/controllers/subsystem/techtree.dm
  code/modules/cm_tech/techtree.dm
Labels: Code Improvement

#351 Round Start delayed by default
  code/controllers/subsystem/ticker.dm
Labels: Admin

#352 Discord button size reduction
  interface/skin.dmf
Labels: UI
