Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-05, with the labels that each got.

#730 HERE WE GO AGAIN: M41AE2 bug fixes.
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
Labels: fix, Feature, Code Improvement, Balance

#942 Remove lrp storage skill checks
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/toolkit.dm
Labels: Removal

#944 Removes the stray white pixel when south-facing for a hairstyle
  icons/mob/humans/human_hair.dmi
Labels: fix, Sprites

#943 hAI factions fixes & tweaks
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_factions.dm
Labels: Quality of Life

#932 acider rouny
  code/__DEFINES/xeno.dm
  code/game/jobs/role_authority.dm
  code/modules/admin/game_master/game_master.dm
  code/modules/mob/living/carbon/xenomorph/castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/strains/castes/runner/acid.dm
  icons/mob/xenos/runner.dmi
  sound/effects/acider.ogg
Labels: Feature, Sprites, Sound

#901 UI: OW Scrolling and misc.
  tgui/packages/tgui/interfaces/OverwatchConsole.jsx
  tgui/packages/tgui/styles/layouts/Layout.scss
Labels: UI, Quality of Life

#754 Blood restoring Chems no longer depend on a Threshold of Nutrition
  code/modules/reagents/chemistry_properties/prop_positive.dm
Labels: Feature, Balance

#890 DMI merge driver now anchors icons for new additions
  tools/dmi/merge_driver.py
Labels: Code Improvement, Stale Exempt

#955 User agents for byond downloads and windows build caching
  .github/workflows/ci_suite.yml
  Dockerfile
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
Labels: Github, Missing Changelog

#937 Throwables in Fire Support Panel
  code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
  tgui/packages/tgui/interfaces/GameMasterFireSupportMenu.jsx
Labels: UI, Feature

#933 Mirror: Fix: Auto verbing for '!' and '? '
  code/__DEFINES/language.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/modules/character_traits/languages.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/languages.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: fix, Feature

#947 UI: Faction Manager + Sentry Laptop Scrolling
  tgui/packages/tgui/interfaces/HumanFactionManager.tsx
  tgui/packages/tgui/interfaces/SentryGunUI.tsx
Labels: fix, UI, Feature

#922 Couple more revived PR's in one
  code/game/objects/effects/decals/posters/poster_list.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/upp.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/masks.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/kitchen_tools.dmi
  icons/obj/structures/props/posters.dmi
Labels: Feature, Sprites, Quality of Life

#958 Zip cuff box size fix
  code/game/objects/items/storage/boxes.dm
Labels: fix

#957 Flashlights, lamps, candles no longer rotate on throw
  code/game/objects/items/devices/flashlight.dm
Labels: Feature

#980 ERT default user selectionfix
  code/modules/admin/topic/topic_events.dm
Labels: Quality of Life

#975 HDR
  code/game/objects/items/reagent_containers/food/mre_food/hdr.dm
  code/game/objects/items/reagent_containers/food/mre_food/uscm.dm
  code/game/objects/items/storage/mre.dm
  code/game/objects/items/trash.dm
  code/modules/projectiles/ammo_boxes/misc_boxes.dm
  code/modules/reagents/chemistry_reagents/food.dm
  colonialmarines.dme
  icons/mob/humans/onmob/inhands/items/mres_lefthand.dmi
  icons/mob/humans/onmob/inhands/items/mres_righthand.dmi
  icons/obj/items/food/mre_food/hdr.dmi
  icons/obj/items/food/mre_food/uscm.dmi
  icons/obj/items/storage/mre.dmi
  icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi
  icons/obj/items/weapons/guns/ammo_boxes/magazines.dmi
Labels: Feature, Sprites

#970 CQC/Injection interaction fixes
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/syringes.dm
Labels: Quality of Life, Balance

#503 Make Arterial Bleeds Disco Again
  code/datums/effects/bleeding.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/prop.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/living_healthscan.dm
  code/modules/organs/limbs.dm
  code/modules/surgery/internal_bleeding.dm
  icons/effects/blood.dmi
  sound/effects/blood_squirt.ogg
  tgui/packages/tgui/interfaces/HealthScan.jsx
Labels: UI, Feature, Sprites, Quality of Life, Mapping, Sound, Balance, Github, Stale Exempt

#969 Claymore tweaks
  code/datums/ammo/shrapnel.dm
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/vehicles/interior/interactable/vendors.dm
Labels: Code Improvement, Balance

#951 Remember Shackleton
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Feature, Mapping

#935 adds heirloom weapons
  code/_globalvars/lists/mapping_globals.dm
  code/game/gamemodes/colonialmarines/ai/colonialmarines_ai.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  icons/landmarks.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/obj/items/storage/kits.dmi
  icons/obj/items/weapons/guns/attachments/rail.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/golden_arrow_classic/golden_arrow_classic.dmm
  maps/map_files/rover/rover.dmm
Labels: Feature, Sprites, Mapping

#974 Slight PMC & WY backend tweaks
  code/datums/emergency_calls/inspection.dm
  code/datums/emergency_calls/pmc.dm
  code/game/jobs/job/special/weyland_yutani.dm
  code/game/objects/effects/landmarks/survivor_spawner.dm
  code/modules/gear_presets/colonist.dm
  code/modules/gear_presets/pmc.dm
  code/modules/mob/living/carbon/human/ai/action_datums/sniper_nest.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_pmc.dm
Labels: Feature

#949 STOP KILLING EACH OTHER WITH TRAINING NADES
  code/game/objects/items/explosives/grenades/marines.dm
Labels: fix

#919 Shower polish
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#983 Port: The great cache update and byond mirror fallback
  .github/actions/restore_or_install_byond/action.yml
  .github/actions/setup_node/action.yml
  .github/alternate_byond_versions.txt
  .github/workflows/autowiki.yml
  .github/workflows/ci_suite.yml
  .github/workflows/generate_documentation.yml
  .github/workflows/run_unit_tests.yml
  dependencies.sh
  tools/ci/build.ps1
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
  tools/ci/install_node.sh
Labels: Code Improvement, Github

#940 Fix Advanced Build Mode Var Copy not changing the Loc of Objects.
  code/modules/buildmode/submodes/advanced.dm
Labels: fix

#966 Play-Admin-Sound changing default selections
  code/modules/admin/verbs/playsound.dm
Labels: UI

#862 Soldier/Drone tuning & 32's Stop Shuttles Melting
  code/game/objects/effects/aliens.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/mob/living/carbon/xenomorph/castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/Soldier.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: fix, Feature, Balance

#643 makes the M41A UBGL work (mostly) like a shotgun
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Feature, Quality of Life, Grammar and Formatting

#925 Adds casings & casing ejection to relevant guns (PR Port)
  code/__DEFINES/conflict.dm
  code/datums/ammo/ammo.dm
  code/datums/ammo/bullet/lever_action.dm
  code/datums/ammo/bullet/pistol.dm
  code/datums/ammo/bullet/revolver.dm
  code/datums/ammo/bullet/rifle.dm
  code/datums/ammo/bullet/shotgun.dm
  code/datums/ammo/bullet/smg.dm
  code/datums/ammo/bullet/sniper.dm
  code/datums/ammo/bullet/special_ammo.dm
  code/game/objects/effects/decals/remains.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/boltaction.dm
  code/modules/projectiles/guns/flare_gun.dm
  code/modules/projectiles/guns/lever_action.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  icons/obj/items/casings.dmi
  maps/map_files/BMG290_Otogi_Egress_Point/BMG290_Otogi_Egress_Point.dmm
  maps/map_files/BigRed/sprinkles/10.prison_breakout.dmm
  maps/map_files/BigRed/standalone/medbay-v3.dmm
  maps/map_files/Calliope_Highway/Calliope_Highway.dmm
  maps/map_files/DesertDam/standalone/crashlanding-upp-bar.dmm
  maps/map_files/FOP_v2_Cellblocks/Prison_Station_FOP.dmm
  maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
  maps/map_files/FOP_v3_Sciannex/sprinkles/20.medicalhold.dmm
  maps/map_files/FOP_v3_Sciannex/sprinkles/20.yardbasketball.dmm
  maps/map_files/FOP_v3_Sciannex/standalone/riot_in_progress.dmm
  maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
  maps/map_files/Ice_Colony_v3/standalone/panic_room_hold.dmm
  maps/map_files/LV624/LV624.dmm
  maps/map_files/LV624/sprinkles/30.nexuscenter_barricaded.dmm
  maps/map_files/LV624/standalone/clfship.dmm
  maps/map_files/LV624/standalone/corporatedome.dmm
  maps/map_files/New_Varadero/New_Varadero.dmm
  maps/map_files/USS_Almayer/USS_Almayer.dmm
  maps/map_files/Whiskey_Outpost_v2/Whiskey_Outpost_v2.dmm
  maps/map_files/derelict_almayer/derelict_almayer.dmm
Labels: Feature, Sprites, Mapping

#709 Ports Human Deathcheck from PVP
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
Labels: Code Improvement, Server

#900 Langchat Max Character Length and Display Width can be Var Edited.
  code/datums/langchat/langchat.dm
Labels: Feature

#989 Human AI now Compare Vehicle Factions to their Neutral and Friendly Factions.
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_helpers.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_targeting.dm
Labels: fix

#924 adds chinese bayonets to UPP loadout
  code/__DEFINES/objects.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/gear_presets/canc.dm
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/obj/items/weapons/weapons.dmi
Labels: Feature, Sprites
