Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-02, with the labels that each got.

#724 Grabbing a xeno no longer floors you for several seconds
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
Labels: Quality of Life, Balance

#722 Fixes squad panel occasionally being blank
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_spawner.dm
Labels: Admin

#689 M39 rebranded - M-77 Viper 9 & gun audio 'fix'
  code/datums/ammo/bullet/pistol.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/ammo_boxes/round_boxes.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/clothing/belts.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
Labels: fix, Feature, Sprites, Balance

#729 LPO80 Incinerator Unit
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/magazines/flamer.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/upp.dmi
  icons/obj/items/weapons/guns/attachments.dmi
  icons/obj/items/weapons/guns/attachments/stock.dmi
  icons/obj/items/weapons/guns/guns_by_faction/upp.dmi
Labels: Feature, Sprites

#683 Ports various QoL PRs from PvP
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/toys/toys.dm
  code/modules/clothing/under/ties.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  tgui/packages/tgui/interfaces/DropshipFlightControl.tsx
Labels: UI, Quality of Life

#711 Ports #7937 from PvP (Gun cursor fixes)
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences_toggles.dm
  code/modules/cm_tech/hologram.dm
  code/modules/cm_tech/implements/railgun.dm
  code/modules/mob/living/carbon/xenomorph/abilities/ability_macro_framework.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/boltaction.dm
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/lever_action.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smartgun.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist/launcher/launcher.dm
  code/modules/projectiles/guns/specialist/scout.dm
  code/modules/projectiles/guns/specialist/sniper.dm
Labels: fix, Refactor

#714 Commitee Approved Unit Doctrine UPP AI Squad Balancing
  code/modules/gear_presets/upp.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_upp.dm
Labels: Feature, Balance

#748 Fixes some Human AI bugs
  code/modules/mob/living/carbon/human/ai/action_datums/item_pickup.dm
  code/modules/mob/living/carbon/human/ai/order_datums/order_patrol.dm
  tgui/packages/tgui/interfaces/HumanAIManager.tsx
  tgui/packages/tgui/interfaces/HumanAISpawner.tsx
Labels: UI, Admin

#734 Fixes UPP Knife not visible on draw
  code/modules/projectiles/gun_attachables.dm
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
Labels: fix, Sprites

#751 typo fixing at Update belt.dm
  code/game/objects/items/storage/belt.dm
Labels: Missing Changelog

#752 Returns smoke grenades to the base Garrow build
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#737 Walking back shotgun ammo knockdown range
  code/datums/ammo/bullet/shotgun.dm
Labels: Feature, Balance

#756 changes how custom items spawn
  code/controllers/subsystem/ticker.dm
  code/modules/customitems/item_spawning.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature

#758 Mapjam Rewards 2025 (actual)
  code/modules/clothing/under/ties.dm
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/ties.dmi
Labels: Feature, Sprites

#746 Resprites HPR, and adds a case for it too
  code/modules/cm_marines/equipment/guncases.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/storage/kits.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
Labels: Feature, Sprites

#715 USCM AI Squads
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_uscm.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_uscm.dm
  colonialmarines.dme
Labels: Stale, Feature

#653 Adds hairstyles from recent PvP Additions
  code/modules/mob/new_player/sprite_accessories/hair.dm
  icons/mob/humans/human_hair.dmi
Labels: Stale, Feature, Sprites

#761 Removes "Treat Ally" Human AI Action
  code/modules/mob/living/carbon/human/ai/action_datums/treat_ally.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_health.dm
  colonialmarines.dme
Labels: Removal

#766 Ports a few more QoL PR's from PVP
  code/modules/mob/living/carbon/human/species/species.dm
  interface/skin.dmf
Labels: Quality of Life

#744 Adjusted rank options for the Section/Platoon
  code/__DEFINES/job.dm
  code/game/jobs/job/command/cic/staffofficer.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/smartgunner.dm
  code/game/jobs/job/marine/squad/standard.dm
  code/game/jobs/job/marine/squad/tl.dm
  code/game/jobs/job/marine/squad_info.dm
  code/game/jobs/job/marine/squads.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/gear_presets/uscm.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
  tgui/packages/tgui/interfaces/OverwatchConsole.jsx
  tgui/packages/tgui/interfaces/SquadInfo.tsx
Labels: UI, Feature, Quality of Life, Mapping, Code Improvement, Removal

#760 Playboy, Soldier of Fortune, Coca-Cola and Pepsi
  code/game/machinery/vending/vending_types.dm
  code/game/objects/effects/decals/posters/poster_list.dm
  code/game/objects/items/reagent_containers/food/cans.dm
  code/game/objects/items/reagent_containers/food/drinks/drinkingglass.dm
  code/game/objects/prop.dm
  code/modules/reagents/chemistry_reagents/drink.dm
  icons/obj/items/drinkcans.dmi
  icons/obj/items/drinks.dmi
  icons/obj/structures/machinery/vending.dmi
  maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
  maps/map_files/LV522_Chances_Claim_FORECON/LV522_Chances_Claim_FORECON.dmm
  maps/map_files/USS_Almayer/USS_Almayer.dmm
  maps/map_files/derelict_almayer/derelict_almayer.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/golden_arrow_classic/golden_arrow_classic.dmm
  maps/map_files/rover/rover.dmm
Labels: Feature, Sprites, Mapping

#772 Vehicle Nuke death fix port
  code/game/machinery/nuclearbomb.dm
Labels: fix

#731 Makes ammo round boxes more distinguishable / Adds special buckshot box
  code/modules/projectiles/ammo_boxes/ammo_boxes.dm
  code/modules/projectiles/ammo_boxes/handful_boxes.dm
  code/modules/projectiles/ammo_boxes/round_boxes.dm
  icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi
Labels: Stale, Feature, Sprites

#740 SPACE. THE FINAL FRONTIER.
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/void.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/gear_presets/upp.dm
  code/modules/gear_presets/uscm.dm
  colonialmarines.dme
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/cm_suits.dmi
  maps/map_files/Ice_Colony_v1/Ice_Colony_v1.dmm
  maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
  maps/map_files/LV522_Chances_Claim_FORECON/LV522_Chances_Claim_FORECON.dmm
  maps/map_files/USS_Almayer/USS_Almayer.dmm
  maps/map_files/derelict_almayer/derelict_almayer.dmm
  maps/templates/Chinook.dmm
Labels: Feature, Sprites, Mapping

#739 Stops Langchat Emotes Hanging Forever from Deleted Turfs.
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/timer.dm
  code/datums/langchat/langchat.dm
Labels: Stale, fix, Feature

#775 Beretta 92FS Updated
  code/modules/projectiles/guns/pistols.dm
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/obj/items/weapons/guns/guns_by_faction/colony.dmi
Labels: Feature, Sprites

#741 stop sentry guns targeting pocket animals
  code/modules/mob/holder.dm
Labels: fix, Feature

#743 MARSOC Arsenal adjustment
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/uscm.dm
  code/modules/projectiles/guns/rifles.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/back.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_obj.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_righthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/suit_slot.dmi
Labels: fix, Feature, Sprites, Code Improvement, Removal

#723 Records are no longer cut off, adds record computers to all shipmaps.
  code/__HELPERS/text.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human.dm
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: fix, Feature, Mapping

#778 Fixes the poor fuel efficiency of campfires
  code/game/objects/structures/props.dm
Labels: Quality of Life

#377 lore accurate MD noises
  sound/items/detector_ping_1.ogg
  sound/items/detector_ping_2.ogg
  sound/items/detector_ping_3.ogg
  sound/items/detector_ping_4.ogg
Labels: Feature, Sound, Stale Exempt

#696 Aux Languages & TWE/LatAm Colonists
  code/__DEFINES/language.dm
  code/_globalvars/lists/names.dm
  code/game/objects/items/pamphlets.dm
  code/modules/character_traits/languages.dm
  code/modules/gear_presets/colonist.dm
  code/modules/mob/language/languages.dm
  code/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: UI, Feature

#783 Improves candle use time
  code/game/objects/items/tools/flame_tools.dm
Labels: Quality of Life

#786 Moves Ethnicity Code to /equipment_preset/
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/colonist.dm
Labels: fix

#791 Reverses #739
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/timer.dm
  code/datums/langchat/langchat.dm
Labels: fix

#703 Committee Approved Naval Construction
  code/__DEFINES/__game.dm
  code/game/machinery/computer/groundside_operations.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/items/devices/binoculars.dm
  code/game/objects/items/misc.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/secure_crates.dm
  code/game/objects/structures/curtains.dm
  code/game/objects/structures/gun_rack.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/gear_presets/fun.dm
  code/modules/gear_presets/uscm_ship.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/obj/items/binoculars.dmi
  icons/obj/items/storage/kits.dmi
  icons/obj/items/upp-items.dmi
  icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi
  icons/obj/items/weapons/guns/ammo_boxes/magazines.dmi
  icons/obj/structures/crates.dmi
  icons/obj/structures/doors/upp/2x1upp_glass_green.dmi
  icons/obj/structures/doors/upp/2x1upp_glass_grey.dmi
  icons/obj/structures/doors/upp/2x1upp_green.dmi
  icons/obj/structures/doors/upp/2x1upp_grey.dmi
  icons/obj/structures/doors/upp/2x1upp_utility.dmi
  icons/obj/structures/doors/upp/uppdoor_glass_green.dmi
  icons/obj/structures/doors/upp/uppdoor_glass_grey.dmi
  icons/obj/structures/doors/upp/uppdoor_green.dmi
  icons/obj/structures/doors/upp/uppdoor_grey.dmi
  icons/obj/structures/doors/upp/uppdoor_utility.dmi
  icons/obj/structures/gun_racks.dmi
  icons/obj/structures/machinery/vending.dmi
  icons/obj/structures/props/curtain.dmi
  icons/turf/floors/strata_floor.dmi
  icons/turf/walls/upp_green.dmi
  icons/turf/walls/upp_green_windows.dmi
  icons/turf/walls/upp_grey.dmi
  icons/turf/walls/upp_grey_windows.dmi
  maps/map_files/chapaev/chapaev.dmm
Labels: Feature, Sprites, Mapping, Sound

#789 Neckerchief
  code/modules/client/preferences_gear.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/shoes/marine_shoes.dm
  icons/mob/humans/onmob/feet.dmi
  icons/mob/humans/onmob/mask.dmi
  icons/obj/items/clothing/masks.dmi
  icons/obj/items/clothing/shoes.dmi
Labels: Feature, Sprites

#747 New Projectile Sprites and Tracer Projectile Support
  code/__DEFINES/colours.dm
  code/datums/ammo/ammo.dm
  code/datums/ammo/bullet/arc.dm
  code/datums/ammo/bullet/rifle.dm
  code/datums/ammo/bullet/special_ammo.dm
  code/datums/ammo/bullet/tank.dm
  code/datums/ammo/rocket.dm
  code/datums/elements/traitbound/gun_silenced.dm
  code/game/machinery/vending/vendor_types/antag/antag_guns_snowflake.dm
  code/modules/cm_preds/yaut_weapons.dm
  code/modules/defenses/sentry.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/projectiles/ammo_boxes/round_boxes.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smartgun.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/apc/apc_aa.dm
  code/modules/vehicles/apc/apc_movie.dm
  code/modules/vehicles/apc/arc.dm
  code/modules/vehicles/apc/arc_weaponless.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/cupola_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/firing_port_weapon_ammo.dm
  code/modules/vehicles/hardpoints/primary/arc_frontal.dm
  code/modules/vehicles/hardpoints/primary/arc_sentry.dm
  code/modules/vehicles/hardpoints/primary/dual_cannon.dm
  code/modules/vehicles/hardpoints/primary/ltb.dm
  code/modules/vehicles/hardpoints/primary/minigun.dm
  code/modules/vehicles/hardpoints/secondary/aa_launcher.dm
  code/modules/vehicles/hardpoints/secondary/cupola.dm
  code/modules/vehicles/hardpoints/secondary/frontal_cannon.dm
  code/modules/vehicles/hardpoints/secondary/tow.dm
  code/modules/vehicles/hardpoints/support/flare.dm
  icons/obj/items/weapons/projectiles.dmi
Labels: Feature, Sprites, Stale Exempt

#806 GMs can now toggle Cade building
  code/__DEFINES/mode.dm
  code/__DEFINES/objects.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/tools/shovel_tools.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/game_master/game_master.dm
Labels: Feature

#801 Use github app for ci
  .github/workflows/auto_changelog.yml
  .github/workflows/compile_changelogs.yml
  .github/workflows/labeler.yml
  .github/workflows/run_approval.yml
  .github/workflows/stale.yml
  .github/workflows/update_changelog.yml
  .github/workflows/update_tgs_dmapi.yml
  tools/mapmerge2/fixup.py
Labels: Github, Missing Changelog

#280 ports sharp rifle
  code/__DEFINES/conflict.dm
  code/datums/ammo/bullet/shotgun.dm
  code/datums/ammo/misc.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/shards.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/projectiles/projectile.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/weapons/grenade.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/lineart.dmi
  icons/obj/items/weapons/projectiles.dmi
  sound/weapons/gun_sharp.ogg
  sound/weapons/gun_sharp_explode.ogg
Labels: Feature, Sprites, Sound, Stale Exempt

#811 Spawn Turf Linked Personal Closets
  code/game/objects/structures/crates_lockers/closets/secure/marine_personal.dm
  code/modules/gear_presets/_select_equipment.dm
Labels: Missing Changelog
