Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-08, with the labels that each got.

#1170 No more playtime-dependant paygrade changes for some prop presets
  code/modules/gear_presets/uscm.dm
Labels: fix, Quality of Life

#1168 More pistol stat tweaks
  code/datums/ammo/bullet/pistol.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/pistols.dm
Labels: fix, Balance

#1169 Flames now correctly burn webs and cocoons
  code/game/objects/effects/spiders.dm
Labels: fix, Balance

#1173 Swiss Army Knife Radial Menu
  code/game/objects/items/weapons/blades.dm
Labels: Quality of Life

#322 Smoke Code Refactor
  code/__DEFINES/atmospherics.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/structures/pipes/vents/vents.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/under/marine_uniform.dm
Labels: UI, Sprites, Mapping, Sound, Code Improvement, Github, Stale Exempt

#1151 GArrow & Inserts missing disposals + Phone & Airlock name consistency + Minor Fix for disposals on nightmare inserts
  code/modules/recycling/disposal.dm
  maps/map_files/golden_arrow/dorms/10.party.dmm
  maps/map_files/golden_arrow/dorms/20.dorks.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/golden_arrow/medbay/10.visceracleanupdetail.dmm
  maps/map_files/golden_arrow/medbay/10.wrongtile.dmm
Labels: fix, Mapping

#728 UPP Vehicle
  code/datums/ammo/misc.dm
  code/datums/ammo/rocket.dm
  code/datums/vehicles.dm
  code/game/turfs/open.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/shuttle/computers/dropship_computer.dm
  code/modules/vehicles/hardpoints/armor/UPP armor.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/minigun_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/p17702.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/railgun.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/smoke_ammo.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/t60p3m.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/tow_ammo.dm
  code/modules/vehicles/hardpoints/holder/apc_turret.dm
  code/modules/vehicles/hardpoints/holder/tank_turret.dm
  code/modules/vehicles/hardpoints/holder/van_turret.dm
  code/modules/vehicles/hardpoints/primary/apc_minigun.dm
  code/modules/vehicles/hardpoints/primary/p17702.dm
  code/modules/vehicles/hardpoints/primary/railgun.dm
  code/modules/vehicles/hardpoints/secondary/Hj35.dm
  code/modules/vehicles/hardpoints/secondary/t60p3m.dm
  code/modules/vehicles/hardpoints/support/flare.dm
  code/modules/vehicles/hardpoints/wheels/apc_wheels.dm
  code/modules/vehicles/hardpoints/wheels/van_wheels.dm
  code/modules/vehicles/interior/areas.dm
  code/modules/vehicles/interior/interactable/seats.dm
  code/modules/vehicles/interior/interactable/vehicle_locker.dm
  code/modules/vehicles/interior/interior_landmarks.dm
  code/modules/vehicles/multitile/multitile_verbs.dm
  code/modules/vehicles/uppapc/interior.dm
  code/modules/vehicles/uppapc/uppapc.dm
  code/modules/vehicles/upptank/interior.dm
  code/modules/vehicles/upptank/upptank.dm
  code/modules/vehicles/uppvan/interior.dm
  code/modules/vehicles/uppvan/uppvan.dm
  colonialmarines.dme
  icons/obj/items/weapons/guns/ammo_by_faction/upp.dmi
  icons/obj/items/weapons/projectiles.dmi
  icons/obj/structures/machinery/toc_upp.dmi
  icons/obj/vehicles/hardpoints/uppapc.dmi
  icons/obj/vehicles/hardpoints/upptank.dmi
  icons/obj/vehicles/hardpoints/van.dmi
  icons/obj/vehicles/interiors/uppapc.dmi
  icons/obj/vehicles/interiors/uppapc_chassis.dmi
  icons/obj/vehicles/interiors/upptank.dmi
  icons/obj/vehicles/interiors/upptank_chassis.dmi
  icons/obj/vehicles/interiors/uppvan.dmi
  icons/obj/vehicles/interiors/uppvan_chassis.dmi
  icons/obj/vehicles/uppapc.dmi
  icons/obj/vehicles/upptank.dmi
  icons/obj/vehicles/uppvan.dmi
  icons/obj/vehicles/uppvan_logistics.dmi
  icons/turf/areas_interiors.dmi
  maps/interiors/uppapc.dmm
  maps/interiors/upptank.dmm
  maps/interiors/uppvan.dmm
  maps/interiors/uppvan_logistics.dmm
  maps/interiors/uppvan_medical.dmm
  maps/interiors/uppvan_prisoner.dmm
  maps/interiors/uppvant.dmm
Labels: Feature, Sprites, Mapping, Stale Exempt

#948 [DNTM] Shotgun belt holster round two, last one was cursed by PR gods
  code/game/objects/items/storage/belt.dm
  code/modules/client/preferences_gear.dm
  icons/mob/humans/onmob/belt.dmi
  icons/obj/items/clothing/belts.dmi
Labels: Feature, Sprites, Balance, Do Not Testmerge

#1182 Gasmask Fix
  icons/mob/humans/onmob/mask.dmi
  icons/mob/humans/species/r_human.dmi
Labels: fix, Sprites, Removal

#1120 UPP Lore Accurate Armoury.
  code/datums/ammo/ammo.dm
  code/datums/ammo/bullet/rifle.dm
  code/datums/ammo/bullet/shotgun.dm
  code/datums/ammo/bullet/sniper.dm
  code/datums/elements/bullet_trait/penetrating/penetrating.dm
  code/datums/elements/bullet_trait/penetrating/weak.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/defenses/sentry.dm
  code/modules/projectiles/ammo_boxes/grenade_boxes.dm
  code/modules/projectiles/ammo_boxes/grenade_packets.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/ammo_boxes/round_boxes.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/specialist/launcher/rocket_launcher.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/sentries.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reagents/chemistry_reagents/other.dm
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/storage/kits.dmi
  icons/obj/items/weapons/guns/ammo_boxes/grenade_markings.dmi
  icons/obj/items/weapons/guns/ammo_boxes/grenades.dmi
  icons/obj/items/weapons/guns/ammo_boxes/text.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/upp.dmi
  icons/obj/items/weapons/guns/guns_by_faction/upp.dmi
  icons/obj/items/weapons/guns/guns_by_map/classic/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/classic/guns_righthand.dmi
  icons/obj/items/weapons/projectiles.dmi
  icons/obj/structures/machinery/defenses/sentry.dmi
Labels: fix, Feature, Sprites, Balance

#1186 quickfix for shotgun belt [DNTM]
  code/modules/client/preferences_gear.dm
Labels: fix

#1183 Small MARSOC tweaks
  code/modules/gear_presets/uscm.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: fix, Feature

#1147 Loadout shotgun tweaks
  code/game/gamemodes/colonialmarines/ai/colonialmarines_ai.dm
  code/game/objects/items/storage/large_holster.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Feature

#1191 Quick and dirty faction fix for the UACG (AGAIN)
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_factions.dm
Labels: Code Improvement

#1178 Chapaev Extra Lockers fix
  maps/map_files/chapaev/chapaev.dmm
Labels: Mapping

#1088 smartgunner backslot options
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
Labels: Feature

#1171 Turns the Harm Intent PB Sidetepping into an Opt in preference. And fix shotguns being sneaky and not PBing
  code/__DEFINES/client_prefs.dm
  code/_onclick/click.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/projectiles/gun.dm
Labels: fix, Feature

#1132 Makes It So You Can Only Put Smartguns On Smartgun Harnesses
  code/modules/clothing/suits/marine_armor/smartgunner.dm
Labels: Balance

#1193 Dropship Flight Control/Tactical Map/Ares Interface/Apollo Interfece UI touch ups.
  code/modules/shuttle/computers/dropship_computer.dm
  tgui/packages/tgui/interfaces/AresInterface.jsx
  tgui/packages/tgui/interfaces/DropshipFlightControl.tsx
  tgui/packages/tgui/interfaces/NavigationShuttle.tsx
  tgui/packages/tgui/interfaces/TacticalMap.tsx
  tgui/packages/tgui/interfaces/WorkingJoe.jsx
  tgui/packages/tgui/styles/themes/crt.scss
Labels: fix, UI

#1153 [DNTM] Additional Armor Paints
  code/modules/client/preferences_gear.dm
  code/modules/clothing/under/ties.dm
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
Labels: Feature, Sprites, Do Not Testmerge

#850 Sekhmet Swamp
  code/__DEFINES/__game.dm
  code/datums/weather/weather_events/si391_sekhmet_swamp.dm
  code/datums/weather/weather_map_holders/si391_sekhmet_swamp.dm
  code/game/area/SI391_Sekhmet_Swamp.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/map_files/SI391_Sekhmet_Swamp/SI391_Sekhmet_Swamp.dmm
  maps/si391_sekhmet_swamp.json
Labels: Mapping

#673 BOSENMORI MAP [LV-624 Reimagined]
  code/__DEFINES/__game.dm
  code/datums/weather/weather_events/bosenmori_basho.dm
  code/datums/weather/weather_map_holders/bosenmori_basho.dm
  code/game/area/Bosenmori_Basho.dm
  code/game/objects/structures/ladders.dm
  code/game/turfs/floors/desert.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/bosenmori_basho.json
  maps/map_files/Bosenmori_Basho/Bosenmori Basho.dmm
Labels: Mapping, Stale Exempt

#874 De-PvPification of spec kits
  code/__DEFINES/conflict.dm
  code/datums/ammo/bullet/sniper.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
  code/game/objects/items/devices/binoculars.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/clothing/suits/marine_armor/ghillie.dm
  code/modules/clothing/suits/marine_armor/spec_fire.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/cm_marines/equipment/kit_boxes.dm
  code/modules/cm_marines/specialist.dm
  code/modules/gear_presets/other.dm
  code/modules/gear_presets/pmc.dm
  code/modules/gear_presets/upp.dm
  code/modules/gear_presets/whiteout.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist/scout.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  code/modules/projectiles/magazines/flamer.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/eyes.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/storage/kits.dmi
  icons/obj/items/weapons/guns/attachments/rail.dmi
Labels: Feature, Sprites, Quality of Life, Removal, Balance

#1054 New tacmap-scan map item
  code/__DEFINES/__game.dm
  code/modules/cm_marines/equipment/maps.dm
  icons/obj/items/devices.dmi
Labels: Stale, Feature, Sprites, Grammar and Formatting

#1195 Rover (non-medical) records consoles no longer access-locked
  maps/map_files/rover/rover.dmm
Labels: Mapping

#1197 Weed-node visual update
  code/modules/cm_aliens/weeds.dm
Labels: Quality of Life

#1189 adds three-hole balaclava to upp loadout
  code/modules/client/preferences_gear.dm
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/humans/onmob/mask.dmi
  icons/obj/items/clothing/masks.dmi
Labels: Feature, Sprites

#707 Marine Food Flavortex & Overhaul
  code/game/machinery/vending/vendor_types/food.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/trash.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/holidays/thanskgiving/decorators.dm
  code/modules/reagents/chemistry_reagents/food.dm
  icons/obj/items/food.dmi
  icons/obj/items/food_canteen.dmi
Labels: Feature, Sprites, Removal

#1175 First-aid Kits Overhaul pt2 - adding a first-aid softpack to each shipmap medical prep
  maps/map_files/firefly/firefly.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: Sprites, Mapping

#1007 Redemption Valley groundmap
  code/__DEFINES/__game.dm
  code/datums/weather/weather_events/redemption_valley.dm
  code/datums/weather/weather_map_holders/redemption_valley.dm
  code/game/area/redemption_valley.dm
  code/game/objects/structures/flora.dm
  code/game/turfs/open.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/map_files/redemption_valley/redemption_valley.dmm
  maps/redemption_valley.json
Labels: Mapping

#858 USCSS Secret Agent PMC shipmap and NSG/PVE
  code/__DEFINES/job.dm
  code/__DEFINES/mode.dm
  code/game/gamemodes/colonialmarines/ai/colonialmarines_ai.dm
  code/game/jobs/job/command/cic/staffofficer.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/smartgunner.dm
  code/game/jobs/job/marine/squad/standard.dm
  code/game/jobs/job/marine/squad/tl.dm
  code/game/jobs/job/marine/squads.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/structures/crates_lockers/closets/secure/marine_personal.dm
  code/global.dm
  code/modules/admin/game_master/extra_buttons/rename_platoon.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/defenses/handheld.dm
  code/modules/defenses/sentry.dm
  code/modules/gear_presets/uscm_ship.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/guns/rifles.dm
  map_config/shipmaps.txt
  maps/map_files/USCSS_Obsidian_Falk/USCSS_Obsidian_Falk.dmm
  maps/map_files/USCSS_Onyx_Karain/USCSS_Onyx_Karain.dmm
  maps/uscss_obsidian_falk.json
  maps/uscss_onyx_karain.json
Labels: Feature, Sprites, Mapping

#999 Binhai Supply Station groundmap
  code/__DEFINES/__game.dm
  code/datums/weather/weather_events/binhai_supply_station.dm
  code/datums/weather/weather_map_holders/binhai_supply_station.dm
  code/game/area/binhai_supply_station.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/binhai_supply_station.json
  maps/map_files/binhai_supply_station/binhai_supply_station.dmm
Labels: Mapping

#1144 Additional roundstart squad-datums
  code/__DEFINES/job.dm
  code/datums/factions/uscm.dm
  code/game/gamemodes/colonialmarines/ai/colonialmarines_ai.dm
  code/game/jobs/job/marine/squads.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/marine_personal.dm
  code/global.dm
Labels: fix, Feature, Quality of Life
