Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-03, with the labels that each got.

#609 BMG-290 Otogi Egress Point (MAPJAM-2025)
  code/__DEFINES/__game.dm
  code/datums/weather/weather_events/bmg290_otogi_egress_point.dm
  code/datums/weather/weather_map_holders/bmg290_otogi_egress_point.dm
  code/game/area/BMG290_Otogi_Egress_Point.dm
  code/game/machinery/doors/railing.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/open.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/bmg290_otogi_egress_point.json
  maps/map_files/BMG290_Otogi_Egress_Point/BMG290_Otogi_Egress_Point.dmm
  tools/UpdatePaths/Scripts/pve609-otogi-varedits.txt
Labels: Mapping, PVE-MAPJAM-2025, Stale Exempt

#814 Otogi fixes for linters
  maps/map_files/BMG290_Otogi_Egress_Point/BMG290_Otogi_Egress_Point.dmm
Labels: Mapping

#719 Explosives overhaul pt3
  code/datums/ammo/rocket.dm
  code/datums/ammo/shrapnel.dm
  code/game/machinery/vending/cm_vending.dm
  code/game/machinery/vending/vending.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/kit_boxes.dm
  code/modules/cm_marines/equipment/mortar/mortar_shells.dm
  code/modules/gear_presets/usa.dm
  code/modules/gear_presets/uscm.dm
  code/modules/projectiles/ammo_boxes/grenade_packets.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist/launcher/rocket_launcher.dm
  icons/obj/items/storage/packets.dmi
  icons/obj/items/weapons/grenade.dmi
  icons/obj/structures/mortar.dmi
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Feature, Sprites, Quality of Life, Mapping, Removal, Balance, Admin

#659 Stop Wrenching tables for metal, and window frames to speed up movement through buildings
  code/game/objects/items/frames/table_rack.dm
  code/game/objects/structures/window_frame.dm
Labels: Stale, Feature, Balance

#823 Apparently I'm blind
  code/datums/skills/usasf.dm
Labels: Grammar and Formatting

#825 Fixes CustomItems entries requiring exact ckey matches
  code/modules/customitems/item_spawning.dm
Labels: fix

#813 Examine shows if human will be shot by IFF+nIFF lets you shoot when stacked on someone.
  code/datums/components/iff_fire_prevention.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: fix, Feature

#721 PMC Overhaul and Balance
  code/__DEFINES/job.dm
  code/datums/emergency_calls/inspection.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/factions/pmc.dm
  code/game/jobs/job/special/weyland_yutani.dm
  code/game/objects/effects/spawners/faction_spawners.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor/ert.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/pmc.dm
  code/modules/gear_presets/whiteout.dm
  code/modules/gear_presets/wy_goons.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_pmc.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/mob/humans/onmob/belt.dmi
  icons/mob/humans/onmob/mask.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/masks.dmi
  maps/map_files/BigRed/sprinkles/40.admin_pmc.dmm
  maps/map_files/BigRed/standalone/crashlanding-offices.dmm
  maps/map_files/LV624/crashedship/10.digsite.dmm
  maps/map_files/LV624/hydro/30.destroyed.dmm
  maps/templates/lazy_templates/weyland_ert_station.dmm
Labels: Sprites, Mapping, Balance

#720 WY Goons Replaced
  code/datums/emergency_calls/goons.dm
  code/modules/gear_presets/colonist.dm
  code/modules/gear_presets/wy_goons.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_wy.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/mob/humans/onmob/contained/wy_goons.dmi
  icons/mob/humans/onmob/head_1.dmi
Labels: Sprites, Balance

#827 L33T RACK
  code/game/objects/structures/gun_rack.dm
  code/modules/projectiles/guns/rifles.dm
  icons/obj/structures/gun_racks.dmi
Labels: Feature, Sprites

#826 Squad 3 & 4 selectable as standard
  code/game/jobs/job/marine/squads.dm
  icons/mob/hud/marine_hud.dmi
  tgui/packages/tgui/interfaces/SquadInfo.tsx
Labels: UI, Sprites, Quality of Life

#738 Further sniper tweaks
  code/datums/ammo/bullet/rifle.dm
  code/datums/ammo/bullet/sniper.dm
  code/game/objects/items/storage/belt.dm
  code/modules/mob/living/carbon/human/ai/ai_equipment.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  icons/mob/humans/onmob/back.dmi
Labels: fix, Sprites, Quality of Life, Code Improvement, Balance

#784 500 cigarettes (New cigarette vendors and cigarette pack)
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/storage/fancy.dm
  icons/obj/items/cigarettes.dmi
  icons/obj/structures/machinery/vending.dmi
  maps/map_files/BigRed/BigRed.dmm
  maps/map_files/CORSAT/Corsat.dmm
  maps/map_files/DesertDam/Desert_Dam.dmm
  maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
  maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
  maps/map_files/Kutjevo/Kutjevo.dmm
  maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
  maps/map_files/LV522_Chances_Claim_FORECON/LV522_Chances_Claim_FORECON.dmm
  maps/map_files/LV624/LV624.dmm
  maps/map_files/LV624_Fixed/LV624_repaired.dmm
  maps/map_files/New_Varadero/New_Varadero.dmm
  maps/map_files/New_Varadero_Fixed/New_Varadero_Repaired.dmm
  maps/map_files/Whiskey_Outpost_v2/Whiskey_Outpost_v2.dmm
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: Feature, Sprites, Mapping

#768 Screen Alert Emblems and Portraits
  code/__DEFINES/__game.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/sounds.dm
  code/_globalvars/bitfields.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/game_master/extra_buttons/screen_alert_menu.dm
  code/modules/admin/game_master/extra_buttons/toggle_intro.dm
  code/modules/gear_presets/uscm_ship.dm
  code/modules/maptext_alerts/command_alert.dm
  code/modules/maptext_alerts/misc_alert.dm
  code/modules/maptext_alerts/screen_alerts.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/shuttle/shuttles/dropship.dm
  code/modules/shuttles/marine_ferry.dm
  code/modules/unit_tests/create_and_destroy.dm
  colonialmarines.dme
  icons/effects/alphacolors.dmi
  icons/mob/hud/actions.dmi
  icons/ui_icons/screen_alert_images.dmi
Labels: Feature, Sprites

#799 Movielike-esque Medical APC
  code/datums/ammo/misc.dm
  code/datums/vehicles.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/vehicles/apc/apc_moviemed.dm
  code/modules/vehicles/hardpoints/hardpoint_ammo/smoke_ammo.dm
  code/modules/vehicles/hardpoints/support/smokelauncher.dm
  code/modules/vehicles/interior/areas.dm
  code/modules/vehicles/interior/interactable/vendors.dm
  colonialmarines.dme
  icons/obj/structures/rollerbed.dmi
  icons/obj/vehicles/hardpoints/apc.dmi
  icons/obj/vehicles/movieapc.dmi
  icons/turf/areas_interiors.dmi
  maps/interiors/apc_moviemed.dmm
Labels: Feature, Sprites, Mapping, Balance

#679 CMB Overhaul 2 & fixes/QoL changes
  code/__DEFINES/job.dm
  code/datums/emergency_calls/cmb.dm
  code/datums/emergency_calls/inspection.dm
  code/datums/map_config.dm
  code/datums/paygrades/factions/other/cmb.dm
  code/game/gamemodes/colonialmarines/huntergames.dm
  code/game/machinery/vending/vendor_types/crew/synthetic.dm
  code/game/objects/effects/landmarks/survivor_spawner.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/cmb.dm
  code/modules/gear_presets/colonist.dm
  code/modules/gear_presets/corpses.dm
  code/modules/gear_presets/synths.dm
  code/modules/gear_presets/upp.dm
  code/modules/gear_presets/uscm_event.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_cmb.dm
  colonialmarines.dme
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/mob.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  maps/map_files/CORSAT/Corsat.dmm
  maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
  maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
  maps/map_files/LV522_Chances_Claim_FORECON/LV522_Chances_Claim_FORECON.dmm
  maps/map_files/LV624/LV624.dmm
  maps/map_files/LV624_Fixed/LV624_repaired.dmm
  maps/map_files/New_Varadero/New_Varadero.dmm
  maps/map_files/New_Varadero_Fixed/New_Varadero_Repaired.dmm
  maps/map_files/chapaev/chapaev.dmm
Labels: fix, Feature, Sprites, Quality of Life, Mapping, Removal

#828 Fixes wrong reagent for dylovene autoinjector
  code/game/objects/items/reagent_containers/autoinjectors.dm
Labels: fix

#579 few upp bugfixes
  code/modules/cm_marines/overwatch.dm
  maps/map_files/chapaev/chapaev.dmm
Labels: Stale, fix, Mapping

#831 upp and pmc sg harnesses name bug fixed
  code/modules/clothing/suits/marine_armor/smartgunner.dm
Labels: fix

#834 [Port] Adds harryob's refactored audio player
  tgui/packages/tgui-panel/audio/player.js
  tgui/packages/tgui-panel/audio/player.ts
Labels: UI, Admin

#835 LV-624 repaired sign sprite
  code/game/objects/structures/landing_signs.dm
  icons/obj/structures/props/landing_signs.dmi
  maps/map_files/LV624/LV624.dmm
Labels: Feature, Sprites, Mapping

#838 A19 magazine boxes
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  icons/obj/items/weapons/guns/ammo_boxes/text.dmi
Labels: Feature, Sprites, Grammar and Formatting, Balance

#638 [MDB IGNORE] Canyon 32B (MAPJAM-2025)
  code/__DEFINES/__game.dm
  code/game/area/Canyon_32B.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/canyon_32b.json
  maps/map_files/Canyon_32B/Canyon_32B.dmm
Labels: Mapping, PVE-MAPJAM-2025, Stale Exempt

#764 Lighting overhaul/Port from PVP
  code/__DEFINES/colours.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/lighting/lighting_mask/lighting_mask.dm
  code/modules/power/lighting.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Stale, Feature, Mapping

#830 [MBDIGNORE] LV-295 Blacksite
  code/__DEFINES/__game.dm
  code/datums/weather/weather_events/lv285_blacksite.dm
  code/datums/weather/weather_map_holders/lv295_blacksite.dm
  code/game/area/LV295_Blacksite.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/lv295_blacksite.json
  maps/map_files/LV295_Blacksite/LV295_Blacksite.dmm
Labels: Feature, Mapping

#845 Verb's IMP overhaul Part 1
  code/game/objects/items/storage/backpack.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/obj/items/clothing/backpacks.dmi
Labels: Feature, Sprites

#815 Fixes spawned humans with IDs to have account numbers
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/other.dm
Labels: Stale, fix

#837 Kills the last of the spec-skill checks on specialist equipment
  code/game/objects/items/devices/binoculars.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/suits/marine_armor/ghillie.dm
  code/modules/clothing/suits/marine_armor/spec_fire.dm
  code/modules/cm_marines/equipment/kit_boxes.dm
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/specialist/scout.dm
Labels: Quality of Life, Removal, Balance

#753 Attachies adjustments
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/lever_action.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smartgun.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/specialist/scout.dm
  icons/obj/items/weapons/guns/attachments/rail.dmi
Labels: Sprites, Quality of Life, Code Improvement, Grammar and Formatting, Balance

#848 UPP armor bug
  code/modules/clothing/suits/marine_armor/ert.dm
  maps/map_files/chapaev/chapaev.dmm
Labels: fix, Mapping

#717 Customisation update (not-so-lite-anymore edition)
  code/__DEFINES/equipment.dm
  code/__DEFINES/origins.dm
  code/_globalvars/global_lists.dm
  code/datums/origin/upp.dm
  code/datums/supply_packs/black_market.dm
  code/game/objects/items/devices/personal_data_transmitter.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/structures/fence.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/clothing_accessories.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/under/ties.dm
  code/modules/clothing/under/under.dm
  code/modules/cm_marines/radar.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  code/modules/surgery/generic.dm
  icons/mob/humans/onmob/eyes.dmi
  icons/mob/humans/onmob/hands.dmi
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/mob/humans/onmob/mask.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/glasses.dmi
  icons/obj/items/clothing/gloves.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/weapons/weapons.dmi
Labels: fix, Feature, Sprites, Quality of Life, Code Improvement, Balance

#840 Fixes Golden Arrow shower curtains
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#788 m2c tweaks
  code/datums/ammo/bullet/special_ammo.dm
  code/modules/cm_marines/m2c.dm
  code/modules/cm_marines/smartgun_mount.dm
Labels: Stale, Balance

#839 Otogi signs
  code/game/objects/structures/landing_signs.dm
  icons/obj/structures/props/landing_signs.dmi
  maps/map_files/BMG290_Otogi_Egress_Point/BMG290_Otogi_Egress_Point.dmm
Labels: Feature, Sprites, Mapping

#777 Adds vehicles (box vans, ambulance, and cop car)
  code/datums/vehicles.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/turfs/open.dm
  code/modules/vehicles/interior/areas.dm
  code/modules/vehicles/van/ambulance.dm
  code/modules/vehicles/van/box_van.dm
  code/modules/vehicles/van/cop_car.dm
  code/modules/vehicles/van/interior.dm
  code/modules/vehicles/van/pizza_van.dm
  colonialmarines.dme
  icons/obj/structures/crates.dmi
  icons/obj/vehicles/ambulance.dmi
  icons/obj/vehicles/box_van.dmi
  icons/obj/vehicles/cop_car.dmi
  icons/obj/vehicles/interiors/box_van_interior.dmi
  icons/obj/vehicles/interiors/pizza_van_interior.dmi
  icons/obj/vehicles/pizza_van.dmi
  maps/interiors/ambulance.dmm
  maps/interiors/box_van.dmm
  maps/interiors/cop_car.dmm
  maps/interiors/pizza_van.dmm
  sound/vehicles/box_van_driving.ogg
  sound/vehicles/box_van_horn.ogg
  sound/vehicles/box_van_overdrive.ogg
  sound/vehicles/siren_honk.ogg
Labels: Stale, Feature, Sprites, Mapping, Sound

#863 Updated PMC Vendor
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/modules/projectiles/guns/pistols.dm
Labels: Feature, Quality of Life

#859 Vehicle names fix
  code/modules/vehicles/van/ambulance.dm
  code/modules/vehicles/van/cop_car.dm
Labels: fix

#767 Fish fear me (Fishing rework/port)
  code/game/objects/effects/decals/cleanable/blood/blood.dm
  code/game/objects/effects/decals/cleanable/cleanable.dm
  code/game/objects/items/ore.dm
  code/game/objects/items/reagent_containers/food/fish_snacks.dm
  code/game/objects/items/reagent_containers/food/snacks/meat.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/prop.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/modules/cm_preds/yaut_weapons.dm
  code/modules/fishing/bait/generic.dm
  code/modules/fishing/datums/generic.dm
  code/modules/fishing/poles/generic.dm
  code/modules/fishing/props/fishing_pole.dm
  icons/obj/items/fishing_atoms.dmi
  maps/map_files/LV624/LV624.dmm
  maps/map_files/LV624_Fixed/LV624_repaired.dmm
  maps/map_files/New_Varadero/New_Varadero.dmm
  maps/map_files/New_Varadero_Fixed/New_Varadero_Repaired.dmm
  sound/misc/bobber_water_splash.ogg
  sound/misc/fishing_Line.ogg
  sound/misc/fishing_fail_splash.ogg
  sound/misc/fishing_set_hook.ogg
Labels: Stale, Feature, Sprites, Mapping, Sound
