Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-06, with the labels that each got.

#985 Reducing Xeno pain inflicted from drags and grabs
  code/__DEFINES/pain.dm
Labels: Balance

#993 Reverts Calliope day-time mods
  code/game/area/Calliope_Highway.dm
  code/game/area/calliope_desert_bus.dm
  tools/UpdatePaths/Scripts/pve609-calliope-eveningtime-area-varedit.txt
Labels: Mapping

#991 Vendor tweaks
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
Labels: Feature, Quality of Life, Removal

#988 Tiny little MRE reagent tweak
  code/modules/reagents/chemistry_reagents/food.dm
Labels: Quality of Life

#1000 Makes heavyduty cable subtypes
  code/modules/power/cable_heavyduty.dm
Labels: Feature

#986 hAI tweaks & fixes
  code/datums/skills/clf.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/gear_presets/twe_rebel.dm
  code/modules/gear_presets/ua_rebel.dm
  code/modules/mob/living/carbon/human/ai/action_datums/fire_at_target.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_items.dm
Labels: fix, needs tested, Balance

#1002 Update byond mirror path for CI
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
Labels: Missing Changelog

#1014 Make all disks size tiny
  code/game/objects/items/disks.dm
Labels: Balance

#1009 Fixes wrong turfs on PMC shuttle
  maps/shuttles/dropship_pmc.dmm
Labels: fix, Mapping

#1010 Rags/Polishing Rags/Towels can no longer be spilled or have a lid
  code/game/objects/items/reagent_containers/glass.dm
Labels: fix

#1027 Port: 30 min timeouts for jobs involving setup node
  .github/workflows/ci_suite.yml
  .github/workflows/run_unit_tests.yml
Labels: Github, Missing Changelog

#1025 Fixes AMMO_PRONETARGET projectile flag
  code/modules/projectiles/projectile.dm
Labels: fix

#1029 Port: Fix for Call and Response emotes, (Rock Paper Scissors etc.)
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/XenoAttacks.dm
Labels: fix

#1022 New button to create records for mob
  code/modules/admin/game_master/game_master.dm
  tgui/packages/tgui/interfaces/GameMaster.jsx
Labels: UI, Feature

#1037 Adds more grenades
  code/game/objects/items/storage/belt.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Quality of Life, Mapping, Balance

#1044 All Marines can use the Weapons Console on the Dropship
  code/game/machinery/computer/dropship_weapons.dm
  maps/shuttles/dropship_pmc.dmm
  maps/shuttles/dropship_upp.dmm
Labels: Mapping, Balance

#1041 Radio Packs open on left click, and use a button for calls
  code/__DEFINES/dcs/signals/atom/signals_atom.dm
  code/datums/components/phone.dm
  code/game/objects/items/storage/backpack.dm
Labels: Quality of Life

#1043 Gives Platoon Corpsman the Medical Skill from Pre-Upstream Merge.
  code/datums/skills/uscm.dm
  code/modules/gear_presets/pmc_pve.dm
  code/modules/gear_presets/uscm.dm
Labels: Balance

#606 [MBD IGNORE] MAPJAM2025 - Oread Garrison
  code/__DEFINES/__game.dm
  code/game/area/Oread_Garrison.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/map_files/Oread_Garrison/oread_garrison.dmm
  maps/oread_garrison.json
Labels: Feature, Mapping, PVE-MAPJAM-2025, Stale Exempt

#939 De-anglicized UPP ranks
  code/__DEFINES/paygrade_defs/upp.dm
  code/datums/paygrades/factions/upp/upp.dm
Labels: Quality of Life, Removal

#1001 Rifleman can now choose the Lance Corporal rank+Rank Selection shows Actual Rank.
  code/game/jobs/job/command/cic/staffofficer.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/smartgunner.dm
  code/game/jobs/job/marine/squad/standard.dm
  code/game/jobs/job/marine/squad/tl.dm
  code/modules/gear_presets/uscm.dm
Labels: fix, Feature, Quality of Life

#1051 Further unit rank tweaks
  code/game/jobs/job/job.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/smartgunner.dm
  code/game/jobs/job/marine/squad/standard.dm
  code/game/jobs/job/marine/squad/tl.dm
  code/modules/gear_presets/uscm.dm
Labels: Quality of Life, Code Improvement

#1004 SG sound replacement
  code/game/sound.dm
  code/modules/projectiles/guns/smartgun.dm
  sound/weapons/gun_smartgun1.ogg
  sound/weapons/gun_smartgun1_rattle.ogg
  sound/weapons/gun_smartgun2.ogg
  sound/weapons/gun_smartgun2_rattle.ogg
  sound/weapons/gun_smartgun3.ogg
  sound/weapons/gun_smartgun3_rattle.ogg
  sound/weapons/gun_smartgun4.ogg
  sound/weapons/gun_smartgun4_rattle.ogg
Labels: Feature, Sound

#1058 Reasonable flask sizes
  code/game/objects/items/reagent_containers/food/drinks.dm
Labels: Balance
