Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-07, with the labels that each got.

#1076 Adds the MS-11 Smart Refill tank to the corpsmans chemical vendor
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/objects/items/reagent_containers/glass.dm
Labels: Feature

#1045 Infected Player Follow Category
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/interfaces/Orbit/index.tsx
  tgui/packages/tgui/interfaces/Orbit/types.ts
Labels: UI, Feature

#1081 Fix concentrated adrenaline and make it much less deadly.
  code/datums/effects/mob_crit/human_crit.dm
  code/datums/effects/pain/human_pain.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: fix, Feature, Balance

#1018 Makes the crew manifest function for non-USCM factions
  code/__DEFINES/job.dm
  code/datums/datacore.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/uscm_ship.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/new_player/new_player.dm
Labels: fix, UI

#1052 Further pistol-calibre tweaks
  code/datums/ammo/bullet/pistol.dm
  code/datums/ammo/bullet/revolver.dm
  code/datums/ammo/bullet/smg.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/smgs.dm
Labels: Balance

#1087 Changes what the vendors call the armor attachments
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
Labels: Grammar and Formatting

#1080 Mirror, Fix: RTO Phone search crash + Fix: "Telephone" and other duplicate names spamming PhoneMenu
  code/datums/components/phone.dm
  code/modules/vehicles/interior/interior_landmarks.dm
  maps/interiors/apc.dmm
  maps/interiors/apc_command.dmm
  maps/interiors/apc_med.dmm
  maps/interiors/apc_movie.dmm
  maps/interiors/apc_no_fpw.dmm
  maps/interiors/arc.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  tgui/packages/tgui/interfaces/PhoneMenu.jsx
Labels: fix, UI, Mapping, Code Improvement

#1063 Adds Polish as a language option
  code/__DEFINES/language.dm
  code/game/objects/items/pamphlets.dm
  code/modules/character_traits/languages.dm
  code/modules/mob/language/languages.dm
  code/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: UI, Feature

#1097 Item attack-delay fixes
  code/_onclick/item_attack.dm
Labels: fix

#1075 Re-adds old berets to pointbuy
  code/modules/client/preferences_gear.dm
Labels: Feature

#1092 Makes the UBGL slightly less annoying to use
  code/modules/projectiles/gun_attachables.dm
Labels: Quality of Life

#1102 Gives The Entrenching Tool The IS_SHARP_ITEM_BIG Flag
  code/game/objects/items/tools/shovel_tools.dm
Labels: Feature

#1077 new hairstyles ported
  code/modules/mob/new_player/sprite_accessories/hair.dm
  icons/mob/humans/human_hair.dmi
Labels: Feature, Sprites

#1069 adds poison teeth
  code/datums/emotes.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/tools/surgery_tools.dm
  code/game/objects/items/trash.dm
  code/modules/gear_presets/upp.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
  code/modules/surgery/implant.dm
  icons/obj/items/items.dmi
  icons/obj/items/surgery_tools.dmi
  sound/items/poison_tooth.ogg
Labels: Feature, Sprites, Sound

#1062 Readds Autodoc Automatic Mode
  code/game/machinery/medical_pod/autodoc.dm
  code/game/machinery/medical_pod/medical_pod.dm
Labels: Feature, Quality of Life, Mapping

#1042 Adjustments to hAI (behaviour & presets)
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/contractor.dm
  code/modules/gear_presets/other.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain.dm
Labels: needs tested, Balance

#1084 Ventcrawl fix for #619
  code/modules/mob/living/living_defines.dm
Labels: fix

#1104 Adds kruft single slices to the long-life foodstuff locker
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/storage/boxes.dm
  icons/obj/items/food.dmi
  icons/obj/items/storage/boxes.dmi
  maps/map_files/BMG290_Otogi_Egress_Point/BMG290_Otogi_Egress_Point.dmm
  maps/map_files/Calliope_Highway/Calliope_Highway.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: Feature, Sprites, Mapping, Removal

#1061 Catches missed UPP job title stuff
  code/__DEFINES/job.dm
  code/modules/clothing/head/helmet.dm
  code/modules/gear_presets/uscm.dm
Labels: fix, UI, Quality of Life

#984 Surface to air missiles
  code/datums/ammo/misc.dm
  code/datums/ammo/rocket.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/specialist/launcher/rocket_launcher.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/obj/items/clothing/backpacks.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/upp.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/attachments/barrel.dmi
  icons/obj/items/weapons/guns/guns_by_faction/upp.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/lineart.dmi
  icons/obj/items/weapons/projectiles.dmi
  sound/weapons/gun_emblr.ogg
  sound/weapons/gun_hornet.ogg
Labels: Feature, Sprites, Sound

#1005 Night Of The Living Dead - Expanded Create HAI Menu Selections
  code/__DEFINES/mode.dm
  code/datums/diseases/black_goo.dm
  code/datums/emergency_calls/zombie.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/clothing/suits/marine_armor/ert.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/canc.dm
  code/modules/gear_presets/colonist.dm
  code/modules/gear_presets/other.dm
  code/modules/gear_presets/synths.dm
  code/modules/gear_presets/twe_rebel.dm
  code/modules/gear_presets/ua_rebel.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/zombie.dm
  code/modules/mob/living/carbon/human/ai/action_datums/mg_nest.dm
  code/modules/mob/living/carbon/human/ai/ai_equipment.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_canc.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_clf.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_cmb.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_colonist.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_contractor.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_elite_mercs.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_freelancer.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_malfunction_synthetic.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_pmc.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_royal_marines.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_twe_rebel.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_upp.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_uscm.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_wy.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_zombies.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_factions.dm
  code/modules/mob/living/carbon/human/species/zombie.dm
  colonialmarines.dme
  tgui/packages/tgui/interfaces/HumanAISpawner.tsx
Labels: UI, Feature

#1121 fixes UACG headset hud define
  code/game/objects/items/devices/radio/headset.dm
Labels: fix

#1089 SG harness & weapon slowdown tweaks
  code/__DEFINES/conflict.dm
  code/modules/clothing/suits/marine_armor/smartgunner.dm
  code/modules/projectiles/guns/smartgun.dm
Labels: Balance

#1056 canc troopers update
  code/__DEFINES/objects.dm
  code/datums/ammo/bullet/rifle.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/canc.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/eyes.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/glasses.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/upp.dmi
  icons/obj/items/weapons/guns/attachments/barrel.dmi
  icons/obj/items/weapons/guns/attachments/rail.dmi
  icons/obj/items/weapons/guns/guns_by_faction/upp.dmi
  icons/obj/items/weapons/guns/lineart.dmi
  icons/obj/items/weapons/weapons.dmi
  sound/weapons/gun_lw317.ogg
Labels: Feature, Sprites, Sound

#1068 US Army update
  code/__DEFINES/job.dm
  code/game/jobs/job/marine/squads.dm
  code/game/objects/items/devices/helmet_visors.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/clothing/suits/marine_armor/intel.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/usa.dm
  icons/mob/hud/marine_hud.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
Labels: Feature, Sprites, Quality of Life, Grammar and Formatting

#879 UA Colonial Guard | Additional sub-roles for Props
  code/__DEFINES/job.dm
  code/__DEFINES/mob_hud.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/radio.dm
  code/controllers/subsystem/communications.dm
  code/datums/factions/cmb.dm
  code/datums/mob_hud.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/client/preferences_toggles.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/colonist.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/ai/action_datums/sniper_nest.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_uacg.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_factions.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_cmb.dm
  code/modules/mob/living/say.dm
  colonialmarines.dme
  icons/mob/humans/onmob/ties.dmi
  icons/obj/items/clothing/ties.dmi
  tgui/packages/tgui-say/styles/colors.scss
  tgui/packages/tgui/constants.ts
Labels: UI, Feature, Sprites

#1136 [DNTM] UPP Random Locker Item Vaporization, Adds Butterfly Knives To The Loadout Item List
  code/game/objects/structures/crates_lockers/closets/secure/marine_personal.dm
  code/modules/client/preferences_gear.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/uscm_ship.dm
  maps/map_files/chapaev/chapaev.dmm
Labels: Feature, Mapping, Do Not Testmerge

#1145 Fixes bug with LatAm Marshals subtypes not spawning with LatAm names
  code/modules/gear_presets/cmb.dm
Labels: fix

#1146 crusher now crushes walls around it
  code/modules/mob/living/carbon/xenomorph/castes/Crusher.dm
Labels: Feature

#1111 Allows You To Put MRE Components Back In
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/mre.dm
Labels: Quality of Life

#1150 Battle-medic sight and army visor fixes
  code/game/objects/items/devices/helmet_visors.dm
  code/modules/clothing/glasses/night.dm
Labels: fix, Balance

#1125 adds a civilian upp over-under shotgun
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/twe_rebel.dm
  code/modules/gear_presets/upp.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/weapons/guns/attachments/barrel.dmi
  icons/obj/items/weapons/guns/attachments/rail.dmi
  icons/obj/items/weapons/guns/attachments/stock.dmi
  icons/obj/items/weapons/guns/guns_by_faction/upp.dmi
  icons/obj/items/weapons/guns/lineart.dmi
  sound/weapons/gun_olympia.ogg
Labels: Feature, Sprites, Sound

#1130 FORECON Presets overhaul
  code/__DEFINES/job.dm
  code/datums/ammo/bullet/pistol.dm
  code/datums/factions/uscm.dm
  code/datums/skills/forecon.dm
  code/game/gamemodes/colonialmarines/ai/colonialmarines_ai.dm
  code/game/jobs/job/marine/squads.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/survivors/lv_522/forcon_survivors.dm
  code/modules/gear_presets/synths.dm
  code/modules/gear_presets/uscm.dm
  code/modules/gear_presets/uscm_forecon.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  code/modules/projectiles/magazines/pistols.dm
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
Labels: fix, Feature, Sprites, Quality of Life, Removal

#1159 MedHUD: Overlay for -100 Health that doesn't make them look dead.
  code/datums/mob_hud.dm
  icons/mob/hud/hud.dmi
Labels: fix, Sprites

#364 Lore Tidbits Update
  code/controllers/subsystem/ticker.dm
  code/modules/client/preferences_toggles.dm
  strings/pvetips.txt
Labels: Missing Changelog

#1164 marines can now get pilot visors as a loadout gear
  code/game/objects/items/devices/helmet_visors.dm
  code/modules/client/preferences_gear.dm
  icons/mob/humans/onmob/helmet_garb.dmi
Labels: Feature, Sprites

#1053 Insurgent Armor - The Armored Van
  code/datums/vehicles.dm
  code/modules/vehicles/hardpoints/primary/van_mg.dm
  code/modules/vehicles/interior/areas.dm
  code/modules/vehicles/van/armored_van.dm
  colonialmarines.dme
  icons/obj/vehicles/van.dmi
  maps/interiors/van_armored.dmm
Labels: Feature, Sprites, Mapping

#1161 PDT Update
  code/game/objects/items/devices/personal_data_transmitter.dm
Labels: Balance

#1156 Chapaev: Extra Lockers
  maps/map_files/chapaev/chapaev.dmm
Labels: Mapping

#1149 [DNTM] M1 Multi-spectrum Visor
  code/game/objects/items/props/helmetgarb.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/helmet.dm
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/mob/humans/species/r_human.dmi
  icons/obj/items/helmet_garb.dmi
Labels: Feature, Sprites, Do Not Testmerge
