Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-04, with the labels that each got.

#857 Fixes MORE Otogi issues
  maps/map_files/BMG290_Otogi_Egress_Point/BMG290_Otogi_Egress_Point.dmm
Labels: Mapping

#867 fix: fix concurrent map reading of same map files
  code/modules/mapping/reader.dm
Labels: fix

#869 AG80 Committee Approved Armament Adjustments
  code/datums/ammo/bullet/rifle.dm
  code/datums/factions/upp.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/structures/gun_rack.dm
  code/modules/gear_presets/upp.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_upp.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/upp.dmi
  icons/obj/items/weapons/guns/attachments.dmi
  icons/obj/items/weapons/guns/attachments/stock.dmi
  icons/obj/items/weapons/guns/attachments/under.dmi
  icons/obj/items/weapons/guns/guns_by_faction/upp.dmi
  icons/obj/items/weapons/guns/lineart.dmi
  icons/obj/structures/gun_racks.dmi
  maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
Labels: Feature, Sprites, Mapping, Removal

#877 AG80 webbing storage fix
  code/modules/clothing/under/ties.dm
Labels: fix

#878 Removes "statis" from the hypersleep pod description
  code/game/machinery/cryopod.dm
Labels: Grammar and Formatting

#880 Adds USCM Headset to FORECON vendor
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/modules/clothing/head/head.dm
Labels: Feature

#873 HAi can now use guns set to burst-mode.
  code/modules/mob/living/carbon/human/ai/action_datums/fire_at_target.dm
  code/modules/projectiles/gun.dm
Labels: fix

#670 [WIP] himat
  code/datums/ammo/shrapnel.dm
  code/game/objects/items/devices/binoculars.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/cm_marines/equipment/mortar/mortar_shells.dm
  code/modules/cm_marines/equipment/mortar/mortars.dm
  icons/mob/hud/actions.dmi
  icons/mob/humans/onmob/back.dmi
  icons/obj/structures/mortar.dmi
Labels: Feature, Sprites

#884 No more baseball-god hAI antics
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_items.dm
Labels: Quality of Life, Balance

#882 prep vendor sprite update
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  icons/obj/structures/machinery/vending.dmi
Labels: Feature, Sprites

#701 Dust Raiders Swept Up
  code/datums/emergency_calls/whiskey_outpost.dm
  code/modules/gear_presets/dust_raider.dm
  colonialmarines.dme
Labels: Stale, Removal

#856 Fix Portrait Announcements being Cut Off and Changes the Sound
  code/modules/maptext_alerts/command_alert.dm
  code/modules/maptext_alerts/misc_alert.dm
Labels: fix

#854 Grenade Box overhaul
  code/datums/agents/tools/decoy.dm
  code/datums/emergency_calls/riot.dm
  code/datums/supply_packs/explosives.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/game/objects/effects/spawners/wo_spawners/supplies.dm
  code/game/objects/items/XMAS.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet/guncabinet.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet/level_blue.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/gear_presets/uscm_event.dm
  code/modules/projectiles/ammo_boxes/ammo_boxes.dm
  code/modules/projectiles/ammo_boxes/box_structures.dm
  code/modules/projectiles/ammo_boxes/grenade_box_structures.dm
  code/modules/projectiles/ammo_boxes/grenade_boxes.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  code/modules/projectiles/item_to_box_mapping.dm
  colonialmarines.dme
  icons/obj/items/storage/packets.dmi
  icons/obj/items/weapons/grenade.dmi
  icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi
  icons/obj/items/weapons/guns/ammo_boxes/grenade_markings.dmi
  icons/obj/items/weapons/guns/ammo_boxes/grenades.dmi
  icons/obj/items/weapons/guns/ammo_boxes/misc.dmi
  maps/map_files/BMG290_Otogi_Egress_Point/BMG290_Otogi_Egress_Point.dmm
  maps/map_files/FOP_v3_Sciannex/standalone/riot_in_progress.dmm
  maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
  maps/map_files/USS_Almayer/USS_Almayer.dmm
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/derelict_almayer/derelict_almayer.dmm
  maps/map_files/firefly/firefly.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: Feature, Sprites, Quality of Life, Mapping, Code Improvement, Removal

#881 Tweaks some of the more egregious non-combat stuns
  code/game/machinery/doors/airlock.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Quality of Life, Balance

#347 M20 Claymore Tweak
  code/__DEFINES/conflict.dm
  code/datums/ammo/shrapnel.dm
  code/game/objects/items/explosives/mine.dm
  code/modules/projectiles/projectile.dm
Labels: Feature, Balance

#895 fix himat deafening
  code/modules/cm_marines/equipment/mortar/mortars.dm
Labels: fix

#745 The weapon of the future, TODAY!
  code/__DEFINES/weapon_stats.dm
  code/datums/ammo/energy.dm
  code/datums/beam.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/effects/effects.dmi
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/obj/items/storage/kits.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/guns_by_map/classic/back.dmi
  icons/obj/items/weapons/guns/guns_by_map/classic/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/classic/guns_obj.dmi
  icons/obj/items/weapons/guns/guns_by_map/classic/guns_righthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/classic/suit_slot.dmi
  icons/obj/items/weapons/guns/guns_by_map/desert/back.dmi
  icons/obj/items/weapons/guns/guns_by_map/desert/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/desert/guns_obj.dmi
  icons/obj/items/weapons/guns/guns_by_map/desert/guns_righthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/desert/suit_slot.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/back.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_obj.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/guns_righthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/jungle/suit_slot.dmi
  icons/obj/items/weapons/guns/guns_by_map/snow/back.dmi
  icons/obj/items/weapons/guns/guns_by_map/snow/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/snow/guns_obj.dmi
  icons/obj/items/weapons/guns/guns_by_map/snow/guns_righthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/snow/suit_slot.dmi
  icons/obj/items/weapons/guns/guns_by_map/urban/back.dmi
  icons/obj/items/weapons/guns/guns_by_map/urban/guns_lefthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/urban/guns_obj.dmi
  icons/obj/items/weapons/guns/guns_by_map/urban/guns_righthand.dmi
  icons/obj/items/weapons/guns/guns_by_map/urban/suit_slot.dmi
  icons/obj/items/weapons/guns/lineart.dmi
  sound/weapons/gun_xm99.ogg
  sound/weapons/handling/gun_xm99_reload.ogg
  sound/weapons/handling/gun_xm99_unload.ogg
Labels: Feature, Sprites, Sound, Code Improvement

#865 More PvP UI Fix Ports & Misc
  .vscode/settings.json
  code/__DEFINES/_click.dm
  code/_onclick/click.dm
  tgui/packages/tgui-panel/audio/player.ts
  tgui/packages/tgui-panel/chat/renderer.tsx
  tgui/packages/tgui/interfaces/MfdPanels/FiremissionPanel.tsx
  tgui/packages/tgui/interfaces/PingRelaysPanel.tsx
Labels: fix, UI

#615 Port Tacmap Polish
  code/__DEFINES/minimap.dm
  code/controllers/subsystem/minimap.dm
  icons/ui_icons/minimap.dmi
  tgui/packages/tgui/interfaces/CanvasLayer.jsx
  tgui/packages/tgui/interfaces/DrawnMap.jsx
  tgui/packages/tgui/interfaces/TacticalMap.tsx
  tgui/packages/tgui/styles/interfaces/TacticalMap.scss
Labels: fix, UI, Sprites, Refactor, Stale Exempt

#853 Mirrors a fix on PvP: Fixes Examining whilst a weapon is in your off-hand.
  code/modules/mob/living/carbon/human/examine.dm
Labels: fix, Feature

#894 Various small fixes
  code/game/machinery/nuclearbomb.dm
  code/game/objects/items/storage/large_holster.dm
  code/modules/clothing/suits/marine_armor/_marine_armor.dm
  code/modules/clothing/suits/marine_armor/ert.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/mob/humans/onmob/inhands/items/bottles_lefthand.dmi
  icons/mob/humans/onmob/inhands/items/bottles_righthand.dmi
  icons/obj/items/drinkcans.dmi
Labels: fix, Sprites, Quality of Life, Grammar and Formatting

#910 [s] Port: Fixes some security issues
  code/datums/datumvars.dm
  code/modules/admin/holder2.dm
Labels: Missing Changelog

#923 UAAF Branch Uniforms
  code/modules/clothing/under/marine_uniform.dm
  code/modules/gear_presets/usasf.dm
  code/modules/projectiles/guns/rifles.dm
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/uniforms.dmi
Labels: Feature, Sprites

#920 Shotgun stuff
  code/datums/ammo/bullet/shotgun.dm
Labels: fix, Sprites, Balance

#916 MRE contents no longer induce yawning
  code/modules/reagents/chemistry_reagents/food.dm
Labels: Quality of Life

#911 Fixes the engineering-geared Para-Rescue preset coming with medical gear
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/under/ties.dm
  code/modules/gear_presets/usasf.dm
  code/modules/projectiles/guns/rifles.dm
Labels: fix

#897 Andro's Shake Groundmap
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/shakeshipverb.dm
  code/modules/almayer/shakeship.dm
Labels: Feature

#904 makes personal closets subtypes for each and every role of each faction
  code/game/objects/structures/crates_lockers/closets/secure/marine_personal.dm
  maps/map_files/chapaev/chapaev.dmm
  maps/map_files/firefly/firefly.dmm
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: Mapping, Code Improvement

#929 Gives LTs their clothes back after Amory stole them
  code/modules/mob/new_player/preferences_setup.dm
Labels: fix

#665 Calliope Valley Maps
  code/__DEFINES/__game.dm
  code/datums/weather/weather_events/calliope_desert_bus.dm
  code/datums/weather/weather_events/calliope_highway.dm
  code/datums/weather/weather_map_holders/calliope_desert_bus.dm
  code/datums/weather/weather_map_holders/calliope_highway.dm
  code/game/area/Calliope_Highway.dm
  code/game/area/calliope_desert_bus.dm
  code/game/turfs/open.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  map_config/maps.txt
  maps/calliope_desert_bus.json
  maps/calliope_highway.json
  maps/map_files/Calliope_Desert_Bus/Calliope_Desert_Bus.dmm
  maps/map_files/Calliope_Highway/Calliope_Highway.dmm
  tools/UpdatePaths/Scripts/pve609-calliope-eveningtime-area-varedit.txt
Labels: Mapping, Stale Exempt

#928 Underbarrel grenade launchers now respect caliber
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/projectiles/gun_attachables.dm
Labels: fix

#934 EEEEEEEEEEEEEEEEEEEEEEEEERM ACKSHUALLY IT'S CALLED HYPERSLEEP
  code/modules/flufftext/Dreaming.dm
Labels: Grammar and Formatting

#905 Resurgent Insurgents
  code/__DEFINES/mode.dm
  code/__DEFINES/origins.dm
  code/__DEFINES/paygrade_defs/canc.dm
  code/__DEFINES/radio.dm
  code/controllers/subsystem/communications.dm
  code/datums/emergency_calls/clf.dm
  code/datums/factions/rebels.dm
  code/datums/origin/upp.dm
  code/datums/paygrades/factions/canc/canc.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor/ert.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/rank_pins.dm
  code/modules/gear_presets/_select_equipment.dm
  code/modules/gear_presets/canc.dm
  code/modules/gear_presets/clf.dm
  code/modules/gear_presets/corpses.dm
  code/modules/gear_presets/other.dm
  code/modules/gear_presets/survivors/misc.dm
  code/modules/gear_presets/twe_rebel.dm
  code/modules/gear_presets/ua_rebel.dm
  code/modules/mob/living/carbon/human/ai/action_datums/sniper_nest.dm
  code/modules/mob/living/carbon/human/ai/ai_equipment.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_clf.dm
  code/modules/mob/living/carbon/human/ai/ai_spawner/ai_presets_freelancer.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_communication.dm
  code/modules/mob/living/carbon/human/ai/brain/ai_brain_factions.dm
  code/modules/mob/living/carbon/human/ai/squad_spawner/squad_clf.dm
  code/modules/projectiles/guns/lever_action.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/pistols.dm
  colonialmarines.dme
  icons/mob/humans/onmob/back.dmi
  icons/mob/humans/onmob/head_1.dmi
  icons/mob/humans/onmob/items_lefthand_1.dmi
  icons/mob/humans/onmob/items_righthand_1.dmi
  icons/mob/humans/onmob/suit_1.dmi
  icons/mob/humans/onmob/suit_slot.dmi
  icons/mob/humans/onmob/ties.dmi
  icons/mob/humans/onmob/uniform_0.dmi
  icons/obj/items/clothing/belts.dmi
  icons/obj/items/clothing/cm_hats.dmi
  icons/obj/items/clothing/cm_suits.dmi
  icons/obj/items/clothing/ties.dmi
  icons/obj/items/clothing/ties_overlay.dmi
  icons/obj/items/clothing/uniforms.dmi
  icons/obj/items/weapons/guns/ammo_by_faction/twe_ammo.dmi
  icons/obj/items/weapons/guns/attachments.dmi
  icons/obj/items/weapons/guns/attachments/rail.dmi
  icons/obj/items/weapons/guns/attachments/stock.dmi
  icons/obj/items/weapons/guns/guns_by_faction/twe_guns.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  icons/obj/items/weapons/guns/lineart.dmi
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: UI, Feature, Sprites, Code Improvement, Removal
