Repository cmss13-devs/cmss13-pve, pull requests merged in 2025-01, with the labels that each got.

#635 Wake up, marines! (Removes salt from prepackaged MREs)
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Removal

#632 Cigarette Garb Hotfix
  icons/mob/humans/onmob/helmet_garb.dmi
Labels: fix, Sprites

#636 Fix Secure Glass Door Opacity
  code/game/machinery/doors/airlock_types.dm
Labels: fix

#645 Security Console in garrow shared office
  code/game/machinery/computer/security.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#649 M20A Unloaded
  code/game/objects/structures/gun_rack.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  icons/obj/structures/gun_racks.dmi
Labels: Feature, Sprites

#648 Midway storage
  maps/shuttles/dropship_midway.dmm
Labels: Mapping

#658 Rover Layer Bug
  maps/map_files/rover/rover.dmm
Labels: Mapping

#657 Adds, Rope ladders, A teleport_vector that hurts you and a darkness tile
  code/game/objects/effects/step_triggers.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/props.dm
Labels: Feature

#261 (mostly)Ignorable weeds
  code/modules/cm_aliens/weeds.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance

#356 Syringe and Liquid Bottles Buff
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/syringes.dm
Labels: Balance

#570 allows lt to change DS name
  code/game/turfs/turf.dm
  code/modules/admin/game_master/extra_buttons/rename_platoon.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/gear_presets/uscm_ship.dm
Labels: Feature

#669 FIXES Headgarb issues
  code/game/objects/items/props/helmetgarb.dm
  code/modules/clothing/head/helmet.dm
  icons/mob/humans/onmob/helmet_garb.dmi
Labels: fix, Feature, Sprites

#671 Remove Non-Crit OD Coffee Jitter
  code/modules/reagents/chemistry_reagents/drink.dm
Labels: Removal

#663 Allows more stuff in APC storage container
  code/modules/vehicles/interior/interactable/vehicle_locker.dm
Labels: Feature

#674 The Flag of the United States of America
  code/game/objects/items/stacks/flags.dm
  icons/obj/structures/plantable_flag.dmi
Labels: Feature, Sprites

#593 More movielike remote-flight console
  code/modules/shuttle/computers/dropship_computer.dm
  icons/obj/structures/machinery/computer.dmi
Labels: Feature, Sprites, Balance

#662 https://i.imgur.com/p2fTnTg.png
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Mapping

#681 XM88 chambers rounds
  code/modules/projectiles/guns/lever_action.dm
Labels: Feature, Quality of Life

#667 Pace yourself - slowed smoking puff animation
  icons/mob/humans/onmob/mask.dmi
Labels: Feature, Sprites

#618 makes christmas less lrp
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/misc.dm
  code/modules/decorators/christmas.dm
  code/modules/gear_presets/_select_equipment.dm
Labels: Stale, Feature

#686 large crates lose their offsets when pulled
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Feature

#585 Prop Language Randomization
  code/modules/gear_presets/clf.dm
  code/modules/gear_presets/cmb.dm
Labels: Stale, Feature

#687 Update stale.yml
  .github/workflows/stale.yml
Labels: Feature, Github, Config

#650 Corpsman Vendor changes
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/modules/clothing/head/helmet.dm
  maps/map_files/golden_arrow/golden_arrow.dmm
Labels: Stale, Feature, Mapping, Removal

#684 Removes APC wheels from Golden Arrow and ERT station
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/templates/lazy_templates/uscm_ert_station.dmm
Labels: Feature, Mapping, Removal

#690 Revert "Prop Language Randomization"
  code/modules/gear_presets/clf.dm
  code/modules/gear_presets/cmb.dm
Labels: Code Improvement

#531 Tech-manual compliant attachment
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/obj/items/weapons/guns/attachments/rail.dmi
  maps/map_files/golden_arrow/golden_arrow.dmm
  maps/map_files/rover/rover.dmm
Labels: do not merge, needs tested, Feature, Sprites, Mapping

#594 Grenade overhaul part 2, the quest for more havoc
  code/__DEFINES/weapon_stats.dm
  code/datums/ammo/shrapnel.dm
  code/datums/supply_packs/explosives.dm
  code/game/machinery/vending/vending_types.dm
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_leader.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_rifleman.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_smartgunner.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/trash.dm
  code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/cm_marines/equipment/mortar/mortar_shells.dm
  code/modules/gear_presets/cmb.dm
  code/modules/gear_presets/uscm_event.dm
  code/modules/gear_presets/uscm_police.dm
  code/modules/projectiles/ammo_boxes/grenade_packets.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist/launcher/grenade_launcher.dm
  icons/obj/items/storage/packets.dmi
  icons/obj/items/weapons/grenade.dmi
  icons/obj/items/weapons/guns/attachments/under.dmi
  icons/obj/structures/mortar.dmi
  maps/map_files/BigRed/sprinkles/20.etatunnel_open.dmm
  maps/map_files/FOP_v3_Sciannex/standalone/riot_in_progress.dmm
  maps/map_files/chapaev/chapaev.dmm
  sound/effects/wp_smoke.ogg
Labels: Feature, Sprites, Quality of Life, Mapping, Sound, Removal, Grammar and Formatting, Balance, Admin

#637 Fix Lizards, Cats and Parrots no longer push you around
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Stale, fix

#678 Stop Sentry Guns from targeting Sentry Gun Laptops
  code/modules/defenses/sentry_computer.dm
Labels: fix, Code Improvement

#472 UpStream Spacebeast
  code/__DEFINES/conflict.dm
  code/__DEFINES/pain.dm
  code/__DEFINES/xeno.dm
  code/game/jobs/role_authority.dm
  code/game/objects/effects/aliens.dm
  code/modules/admin/game_master/game_master.dm
  code/modules/admin/game_master/game_master_submenu/ambush.dm
  code/modules/admin/holder2.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/life/handle_grabbed.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
  code/modules/mob/living/carbon/xenomorph/ai/movement/base_define.dm
  code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
  code/modules/mob/living/carbon/xenomorph/castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/Soldier.dm
  code/modules/mob/living/carbon/xenomorph/castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/projectiles/guns/flare_gun.dm
  colonialmarines.dme
  icons/mob/xenos/soldier.dmi
  icons/mob/xenos/wounds.dmi
Labels: fix, Feature, Sprites, Code Improvement, Stale Exempt

#695 Re-education: A slight edit to the people's handbook
  code/game/objects/prop.dm
Labels: fix, Feature

#697 American flag banner & updated flag banners
  code/game/objects/structures/signs.dm
  icons/obj/structures/props/banners.dmi
Labels: Feature, Sprites

#694 Strata Set Doors
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/multi_tile.dm
  icons/obj/structures/doors/strata/strata_2x1.dmi
  icons/obj/structures/doors/strata/strata_utility.dmi
  maps/map_files/chapaev/chapaev.dmm
Labels: Feature, Sprites, Mapping

#647 Flavour Text and Character Records can now be Longer.
  code/__DEFINES/text.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
Labels: UI

#634 Allows helmet accessory slots to contain most eyewear
  code/modules/clothing/glasses/glasses.dm
Labels: Quality of Life

#668 22nd Century Barbarism - Yautja flaying and hanging made accessible
  code/game/objects/items/stacks/predator.dm
  code/modules/cm_preds/yaut_items.dm
  code/modules/cm_preds/yaut_weapons.dm
Labels: Feature, Quality of Life

#708 Committee Approved Tobacco Products Laika Cigarettes
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/clothing/head/helmet.dm
  icons/mob/humans/onmob/helmet_garb.dmi
  icons/obj/items/cigarettes.dmi
  icons/obj/structures/machinery/vending.dmi
Labels: Feature, Sprites

#698 Sharpened Blades: Knives Update
  code/__DEFINES/surgery.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/under/under.dm
  code/modules/projectiles/gun_attachables.dm
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/obj/items/weapons/guns/attachments.dmi
  icons/obj/items/weapons/guns/attachments/barrel.dmi
  icons/obj/items/weapons/weapons.dmi
Labels: Feature, Sprites, Removal

#677 Ports #7536 from PvP, 'Adds crosshairs to all ranged weapons'
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/cm_preds/yaut_bracers.dm
  code/modules/cm_preds/yaut_weapons.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/boltaction.dm
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/lever_action.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smartgun.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist/launcher/launcher.dm
  code/modules/projectiles/guns/specialist/scout.dm
  code/modules/projectiles/guns/specialist/sniper.dm
  icons/effects/mouse_pointer/explosive_mouse.dmi
  icons/effects/mouse_pointer/flamer_mouse.dmi
  icons/effects/mouse_pointer/lmg_mouse.dmi
  icons/effects/mouse_pointer/pistol_mouse.dmi
  icons/effects/mouse_pointer/plasma_caster_mouse.dmi
  icons/effects/mouse_pointer/rifle_mouse.dmi
  icons/effects/mouse_pointer/shotgun_mouse.dmi
  icons/effects/mouse_pointer/smartgun_mouse.dmi
  icons/effects/mouse_pointer/sniper_mouse.dmi
Labels: Feature, Sprites

#710 properly removes one of the admin verbs upon deadmin
  code/modules/admin/admin_verbs.dm
Labels: Missing Changelog

#706 Committee Approved Nutrient Sources UPP Food Trays
  code/game/machinery/vending/vendor_types/food.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/items/reagent_containers/food/drinks/bottle.dm
  code/game/objects/items/trash.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/reagents/chemistry_machinery/chem_dispenser.dm
  icons/obj/items/drinks.dmi
  icons/obj/items/food.dmi
  icons/obj/structures/machinery/vending_32x64.dmi
  maps/map_files/chapaev/chapaev.dmm
Labels: Feature, Sprites, Mapping

#298 Heavy Pulse RIfle Rework
  code/datums/emergency_calls/supplies.dm
  code/datums/supply_packs/ammo.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/cm_marines/equipment/guncases.dm
  code/modules/cm_marines/equipment/kit_boxes.dm
  code/modules/gear_presets/contractor.dm
  code/modules/gear_presets/other.dm
  code/modules/gear_presets/usa.dm
  code/modules/mob/living/carbon/human/ai/ai_equipment.dm
  code/modules/projectiles/ammo_boxes/magazine_boxes.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/vehicles/interior/interactable/vendors.dm
  icons/obj/items/weapons/guns/attachments.dmi
  icons/obj/items/weapons/guns/attachments/under.dmi
  icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  maps/map_files/LV522_Chances_Claim_FORECON/LV522_Chances_Claim_FORECON.dmm
  maps/templates/lazy_templates/uscm_ert_station.dmm
Labels: fix, Feature, Sprites, Quality of Life, Mapping, Code Improvement, Balance

#713 Adjustments to the King strain of xenomorph
  code/modules/mob/living/carbon/xenomorph/castes/king.dm
  icons/mob/xenos/wounds.dmi
Labels: Sprites, Balance

#675 Pulse Rifle Sound Update: The Reflangening
  code/game/sound.dm
  code/modules/projectiles/guns/rifles.dm
  sound/weapons/gun_m41a_1f.ogg
  sound/weapons/gun_m41a_2f.ogg
  sound/weapons/gun_m41a_3f.ogg
  sound/weapons/gun_m41a_4f.ogg
  sound/weapons/gun_m41a_5f.ogg
  sound/weapons/gun_m41a_6f.ogg
Labels: Sound

#725 Comittee Approved Military Technology Developments
  code/game/objects/items/devices/motion_detector.dm
  code/modules/cm_marines/equipment/guncases.dm
  icons/mob/humans/onmob/items_lefthand_0.dmi
  icons/mob/humans/onmob/items_righthand_0.dmi
  icons/obj/items/storage/kits.dmi
  icons/obj/items/upp-items.dmi
Labels: Feature, Sprites

#588 Nuclear-detonation adjustments and round-start silence
  code/__DEFINES/__game.dm
  code/datums/emergency_calls/emergency_call.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/machinery/nuclearbomb.dm
  sound/theme/nuclear_klaxon.ogg
Labels: Stale, Quality of Life, Sound
